#ifndef FOC_CFG_INIT_VALUES_H
#define FOC_CFG_INIT_VALUES_H

/* Platform timing base and timer source setup. */
#define FOC_PLATFORM_BASE_CLOCK_KHZ 120000U

/* Scheduler rates. */
#define FOC_SCHEDULER_TICK_HZ 1000U
#define FOC_SCHEDULER_CONTROL_HZ 1000U
#define FOC_SCHEDULER_SERVICE_HZ 200U
#define FOC_SCHEDULER_MONITOR_HZ 200U
#define FOC_SCHEDULER_HEARTBEAT_HZ 1U

/*PWM initialization defaults.*/
#define FOC_PWM_FREQ_KHZ                24U
#define FOC_SENSOR_SAMPLE_FREQ_KHZ      FOC_PWM_FREQ_KHZ
#define FOC_SVPWM_DEADTIME_PERCENT_DEFAULT 2U

/* Fast current-loop execute every N PWM update interrupts. */
#define FOC_CURRENT_LOOP_ISR_FREQ    12U
#define FOC_CURRENT_LOOP_ISR_DIVIDER (FOC_PWM_FREQ_KHZ / FOC_CURRENT_LOOP_ISR_FREQ)
/* ADC averaging windows: slow loop for observability, fast loop for current ISR latency. */
#define FOC_SENSOR_ADC_AVG_COUNT_SLOW   24U
#define FOC_SENSOR_ADC_AVG_COUNT_FAST   (FOC_SENSOR_ADC_AVG_COUNT_SLOW / FOC_CURRENT_LOOP_ISR_DIVIDER)
#define FOC_CONTROL_DT_SEC              (1.0f / (float)FOC_SCHEDULER_CONTROL_HZ)

/* Motor initialization parameters. */
#define FOC_MOTOR_INIT_VBUS_DEFAULT 12.0f
#define FOC_MOTOR_INIT_SET_VOLTAGE_DEFAULT 11.4f
#define FOC_MOTOR_INIT_PHASE_RES_DEFAULT 13.2f

/* Alignment/calibration voltage is derived from set_voltage. */
#define FOC_MOTOR_INIT_MECH_ZERO_DEFINED FOC_CFG_ENABLE
#define FOC_MOTOR_INIT_POLE_PAIRS_DEFAULT 7U
#define FOC_MOTOR_INIT_MECH_ZERO_DEFAULT_RAD FOC_MECH_ANGLE_AT_ELEC_ZERO_UNDEFINED//5.265f
#define FOC_MOTOR_INIT_DIRECTION_DEFAULT FOC_DIR_UNDEFINED//FOC_DIR_NORMAL

/* Initialization calibration strategy defaults (coarse + fine subdivision). */
#define FOC_CALIB_ALIGN_VOLTAGE_RATIO 0.60f 
#define FOC_CALIB_SETTLE_MS 4U
#define FOC_CALIB_MIN_MECH_STEP_RAD 0.0015f
#define FOC_CALIB_ZERO_LOCK_SETTLE_MS 120U
#define FOC_CALIB_ZERO_LOCK_SAMPLE_COUNT 24U

#define FOC_CALIB_COARSE_STEP_COUNT 30U
#define FOC_CALIB_FINE_STEP_COUNT 60U
#define FOC_CALIB_COARSE_STEP_ELEC_RAD (FOC_MATH_TWO_PI / (float)FOC_CALIB_COARSE_STEP_COUNT)
#define FOC_CALIB_FINE_STEP_ELEC_RAD (FOC_MATH_TWO_PI / (float)FOC_CALIB_FINE_STEP_COUNT)
#define FOC_CALIB_COARSE_STEP_SETTLE_MS 4U
#define FOC_CALIB_COARSE_STEP_SAMPLE_COUNT 2U
#define FOC_CALIB_FINE_STEP_SETTLE_MS 6U
#define FOC_CALIB_FINE_STEP_SAMPLE_COUNT 4U

/* Control mode default selection and initialization. */
#if (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_FULL)
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE
#elif (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_SPEED_ONLY)
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ONLY
#elif (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_SPEED_ANGLE_ONLY)
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE
#endif
#define COMMAND_MANAGER_DEFAULT_TARGET_ANGLE_RAD 3.14f
#define COMMAND_MANAGER_DEFAULT_ANGLE_SPEED_RAD_S 18.0f
#define COMMAND_MANAGER_DEFAULT_SPEED_ONLY_RAD_S 2.0f

/* Runtime default flags and rates. */
#define COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED FOC_CFG_DISABLE
#define COMMAND_MANAGER_DEFAULT_OSC_ENABLED FOC_CFG_ENABLE
#define COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE FOC_CFG_ENABLE
#define COMMAND_MANAGER_DEFAULT_SEMANTIC_FREQ_HZ 2U
#define COMMAND_MANAGER_DEFAULT_OSC_FREQ_HZ 100U

/* Telemetry default parameter visibility switches and derived mask. */
#define FOC_PROTOCOL_LOCAL_DRIVER_ID_DEFAULT 0x61U //'a'
#define DEBUG_STREAM_OSC_HEAD_BYTE 0x61U
#define DEBUG_STREAM_OSC_TAIL_BYTE 0x62U
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_A FOC_CFG_ENABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_B FOC_CFG_ENABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_C FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_FILTERED FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_ACCUM FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_EXEC_TIME_US FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_VBUS_VOLTAGE FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_IQ_TARGET FOC_CFG_ENABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_IQ_MEASURED FOC_CFG_ENABLE

/* Sensor and filter initialization defaults. */
#define FOC_SENSOR_SAMPLE_OFFSET_PERCENT_DEFAULT 45.0f

#define FOC_SENSOR_KALMAN_CURRENT_A_MEAS_ERR 0.4f
#define FOC_SENSOR_KALMAN_CURRENT_A_EST_ERR 0.0f
#define FOC_SENSOR_KALMAN_CURRENT_A_PROC_NOISE 0.025f
#define FOC_SENSOR_KALMAN_CURRENT_A_INIT 0.0f
#define FOC_SENSOR_KALMAN_CURRENT_B_MEAS_ERR 0.4f
#define FOC_SENSOR_KALMAN_CURRENT_B_EST_ERR 0.0f
#define FOC_SENSOR_KALMAN_CURRENT_B_PROC_NOISE 0.02f
#define FOC_SENSOR_KALMAN_CURRENT_B_INIT 0.0f
#define FOC_SENSOR_KALMAN_ANGLE_MEAS_ERR 0.005f
#define FOC_SENSOR_KALMAN_ANGLE_EST_ERR 0.001f
#define FOC_SENSOR_KALMAN_ANGLE_PROC_NOISE 0.001f
#define FOC_SENSOR_KALMAN_ANGLE_INIT 0.0f
#define FOC_SENSOR_ANGLE_LPF_ALPHA 0.30f

/* Safety threshold defaults. */
#define FOC_DIAG_SENSOR_FAULT_THRESHOLD 1U
#define FOC_UNDERVOLTAGE_TRIP_VBUS_DEFAULT 8.0f

/* Control loop defaults and limits. */
#define FOC_SPEED_ERR_ACCUM_LIMIT_RAD (FOC_MATH_TWO_PI * 4.0f)
/* Unused-macro audit tag: RESERVED_OR_LEGACY_CANDIDATE (pending classification). */
#define FOC_SPEED_MECH_REBASE_RAD 2048.0f
#define FOC_DEFAULT_MIN_MECH_ANGLE_ACCUM_DELTA_RAD 0.001f
#define FOC_DEFAULT_ANGLE_HOLD_INTEGRAL_LIMIT 0.05f
#define FOC_DEFAULT_ANGLE_HOLD_PID_DEADBAND_RAD 0.005f
#define FOC_DEFAULT_SPEED_ANGLE_TRANSITION_START_RAD 0.60f
#define FOC_DEFAULT_SPEED_ANGLE_TRANSITION_END_RAD 1.0f

#define FOC_SVPWM_PRE_LPF_ALPHA 0.20f
#define FOC_ZERO_VECTOR_CLAMP_VOLTAGE_THRESHOLD_V 0.1f

/* PID default gains. */
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KP 2.0f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KI 0.8f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KD 0.01f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KP 0.8f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KI 0.6f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KD 0.005f

#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KP 4.0f
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KI 60.0f
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KD 0.00f

#define FOC_CURRENT_LOOP_ERROR_DEADBAND_A 0.05f
#define FOC_CURRENT_LOOP_INTEGRAL_SUPPRESS_LEAK 0.98f

#define FOC_CURRENT_LOOP_IQ_LPF_ALPHA 0.7f  //Current-loop iq low-pass filter alpha in [0,1]. Higher alpha keeps more bandwidth.

/* Current-loop anti-noise and soft-switch defaults. */
#define COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_ENABLE FOC_CFG_ENABLE
#define COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_MODE FOC_CURRENT_SOFT_SWITCH_MODE_AUTO
#define COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_AUTO_OPEN_IQ_A 0.20f
#define COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_AUTO_CLOSED_IQ_A 0.50f

#define FOC_CURRENT_SOFT_SWITCH_BLEND_TAU_DEFAULT_SEC 0.60f

/* Cogging compensation defaults (optional feature). */
#define FOC_COGGING_LUT_POINT_COUNT 128U
#define FOC_COGGING_LUT_IQ_LSB_A 0.005f
#define FOC_COGGING_COMP_SPEED_GATE_RAD_S 6.0f
#define FOC_COGGING_COMP_IQ_LIMIT_A 0.50f

#define FOC_COGGING_STATIC_TABLE_DEFINED FOC_CFG_DISABLE
#define FOC_COGGING_STATIC_HARMONIC_ORDER 12U
#define FOC_COGGING_STATIC_HARMONIC_AMPLITUDE_A 0.12f
#define FOC_COGGING_STATIC_HARMONIC_PHASE_RAD 0.0f

#define FOC_COGGING_LEARN_STEP_SETTLE_MS 1U
#define FOC_COGGING_LEARN_SAMPLE_COUNT 6U
#define FOC_COGGING_LEARN_MIN_VALID_PERCENT 70U
#define FOC_COGGING_LEARN_ERR_TO_IQ_GAIN_A_PER_RAD 0.50f
#define FOC_COGGING_LEARN_MAX_RETRIES 3U

/* Cogging calibration (user-triggered, runtime) defaults. */
#define FOC_COGGING_CALIB_SPEED_RAD_S 0.1f
#define FOC_COGGING_CALIB_IQ_BASELINE_A 0.015f
#define FOC_COGGING_CALIB_SAMPLES_PER_POINT 16U
#define FOC_COGGING_CALIB_NUM_PASSES 3U
#define FOC_COGGING_CALIB_SETTLE_CYCLES 50U

/*LED initialization defaults. */
#define FOC_LED_RUN_INDEX 1U
#define FOC_LED_COMM_INDEX 2U
#define FOC_LED_FAULT_INDEX 3U
#define FOC_LED_RUN_BLINK_HALF_PERIOD_TICKS 100U
#define FOC_LED_COMM_PULSE_TICKS 10U

#endif /* FOC_CFG_INIT_VALUES_H */
