#ifndef FOC_CFG_SYMBOL_DEFS_H
#define FOC_CFG_SYMBOL_DEFS_H

/* Unified binary semantics for all enable or disable style macros. */
#define FOC_CFG_DISABLE 0U
#define FOC_CFG_ENABLE 1U

/* Control mode options. */
#define COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE 0U
#define COMMAND_MANAGER_CONTROL_MODE_SPEED_ONLY 1U

#define FOC_DIR_UNDEFINED 0
#define FOC_DIR_NORMAL 1
#define FOC_DIR_REVERSED -1

#define FOC_MECH_ANGLE_AT_ELEC_ZERO_UNDEFINED (-1.0f)

#define FOC_POLE_PAIRS_UNDEFINED 0U

/* Current soft-switch mode options. */
#define FOC_CURRENT_SOFT_SWITCH_MODE_OPEN 0U
#define FOC_CURRENT_SOFT_SWITCH_MODE_CLOSED 1U
#define FOC_CURRENT_SOFT_SWITCH_MODE_AUTO 2U

/* Compensation source identifiers. */
#define FOC_COGGING_COMP_SOURCE_DISABLED 0U
#define FOC_COGGING_COMP_SOURCE_NONE 1U
#define FOC_COGGING_COMP_SOURCE_STATIC 2U
#define FOC_COGGING_COMP_SOURCE_CALIB 3U

/* Runtime boolean state representation. */
/* Deprecated alias group: use FOC_CFG_DISABLE/FOC_CFG_ENABLE directly in new code. */
#define COMMAND_MANAGER_ENABLED_DISABLE FOC_CFG_DISABLE
#define COMMAND_MANAGER_ENABLED_ENABLE FOC_CFG_ENABLE

/* Control algorithm build set identifiers. */
#define FOC_CTRL_ALGO_BUILD_FULL 0U
#define FOC_CTRL_ALGO_BUILD_SPEED_ONLY 1U
#define FOC_CTRL_ALGO_BUILD_SPEED_ANGLE_ONLY 2U

/* Protocol frame and status chars (canonical names). */
#define FOC_PROTOCOL_FRAME_HEAD_CHAR 'a'
#define FOC_PROTOCOL_FRAME_TAIL_CHAR 'b'
#define FOC_PROTOCOL_DRIVER_ID_BROADCAST 0xFFU
#define FOC_PROTOCOL_STATUS_OK_CHAR 'O'
#define FOC_PROTOCOL_STATUS_FRAME_ERROR_CHAR 'E'
/* Reserved status char for future timeout feedback path. */
#define FOC_PROTOCOL_STATUS_TIMEOUT_CHAR 'T'

#define PROTOCOL_PARSER_RX_MAX_LEN 64U
#define PROTOCOL_PARSER_MIN_FRAME_LEN 5U

/* Command group definitions. */
#define COMMAND_MANAGER_CMD_PARAM 'P'
#define COMMAND_MANAGER_CMD_STATE 'S'
#define COMMAND_MANAGER_CMD_SYSTEM 'Y'

/* System sub-command definitions. */
#define COMMAND_MANAGER_SYSTEM_SUBCMD_RUNTIME_SUMMARY 'R'
#define COMMAND_MANAGER_SYSTEM_SUBCMD_FAULT_CLEAR_REINIT 'C'
#define COMMAND_MANAGER_SYSTEM_SUBCMD_COGGING_CALIB 'G'
#define COMMAND_MANAGER_SYSTEM_SUBCMD_COGGING_DUMP 'D'
#define COMMAND_MANAGER_SYSTEM_SUBCMD_COGGING_EXPORT 'T'


/* Parameter sub-command definitions. */
#define COMMAND_MANAGER_PARAM_SUBCMD_TARGET_ANGLE 'A'
#define COMMAND_MANAGER_PARAM_SUBCMD_ANGLE_SPEED 'R'
#define COMMAND_MANAGER_PARAM_SUBCMD_SPEED_ONLY_SPEED 'S'
#define COMMAND_MANAGER_PARAM_SUBCMD_SENSOR_SAMPLE_OFFSET 'W'
#define COMMAND_MANAGER_PARAM_SUBCMD_SEMANTIC_DIV 'L'
#define COMMAND_MANAGER_PARAM_SUBCMD_OSC_DIV 'H'
#define COMMAND_MANAGER_PARAM_SUBCMD_OSC_PARAM_MASK 'O'
#define COMMAND_MANAGER_PARAM_SUBCMD_READ_ALL 'X'

/* PID and control config parameter sub-command definitions. */
#define COMMAND_MANAGER_PARAM_SUBCMD_PID_CURRENT_KP 'C'
#define COMMAND_MANAGER_PARAM_SUBCMD_PID_CURRENT_KI 'I'
#define COMMAND_MANAGER_PARAM_SUBCMD_PID_CURRENT_KD 'J'
#define COMMAND_MANAGER_PARAM_SUBCMD_PID_ANGLE_KP 'G'
#define COMMAND_MANAGER_PARAM_SUBCMD_PID_ANGLE_KI 'K'
#define COMMAND_MANAGER_PARAM_SUBCMD_PID_ANGLE_KD 'N'
#define COMMAND_MANAGER_PARAM_SUBCMD_PID_SPEED_KP 'P'
#define COMMAND_MANAGER_PARAM_SUBCMD_PID_SPEED_KI 'U'
#define COMMAND_MANAGER_PARAM_SUBCMD_PID_SPEED_KD 'V'
#define COMMAND_MANAGER_PARAM_SUBCMD_CFG_MIN_MECH_DELTA 'M'
#define COMMAND_MANAGER_PARAM_SUBCMD_CFG_HOLD_I_LIMIT 'B'
#define COMMAND_MANAGER_PARAM_SUBCMD_CFG_HOLD_DEADBAND 'E'
#define COMMAND_MANAGER_PARAM_SUBCMD_CFG_BLEND_START 'F'
#define COMMAND_MANAGER_PARAM_SUBCMD_CFG_BLEND_END 'T'
#define COMMAND_MANAGER_PARAM_SUBCMD_COGGING_CALIB_GAIN 'Y'
#define COMMAND_MANAGER_PARAM_SUBCMD_CONTROL_MODE 'D'
#define COMMAND_MANAGER_PARAM_SUBCMD_CURRENT_SOFT_SWITCH_MODE 'Q'
#define COMMAND_MANAGER_PARAM_SUBCMD_COGGING_COMP_IQ_LIMIT 'U'
#define COMMAND_MANAGER_PARAM_SUBCMD_COGGING_COMP_SPEED_GATE 'V'

/* State sub-command definitions (ENABLE/DISABLE only). */
#define COMMAND_MANAGER_STATE_SUBCMD_MOTOR_ENABLE 'M'
#define COMMAND_MANAGER_STATE_SUBCMD_SEMANTIC_ENABLE 'S'
#define COMMAND_MANAGER_STATE_SUBCMD_OSC_ENABLE 'O'
#define COMMAND_MANAGER_STATE_SUBCMD_CURRENT_SOFT_SWITCH_ENABLE 'C'
#define COMMAND_MANAGER_STATE_SUBCMD_COGGING_COMP_ENABLE 'G'
#define COMMAND_MANAGER_STATE_SUBCMD_READ_ALL 'X'

/* Command status chars. */
#define COMMAND_MANAGER_STATUS_CMD_INVALID_CHAR 'I'
#define COMMAND_MANAGER_STATUS_PARAM_INVALID_CHAR 'P'

/* Communication buffering. */
#define COMMAND_MANAGER_REPLY_BUFFER_LEN 72U

/* Telemetry protocol bytes and payload symbols. */
#define DEBUG_STREAM_OSC_PAYLOAD_LEN 80U

/* Telemetry parameter mask bits. */
#define DEBUG_STREAM_OSC_PARAM_CURRENT_A      0x0001U
#define DEBUG_STREAM_OSC_PARAM_CURRENT_B      0x0002U
#define DEBUG_STREAM_OSC_PARAM_CURRENT_C      0x0004U
#define DEBUG_STREAM_OSC_PARAM_ANGLE_FILTERED 0x0008U
#define DEBUG_STREAM_OSC_PARAM_ANGLE_ACCUM    0x0010U
#define DEBUG_STREAM_OSC_PARAM_EXEC_TIME_US   0x0020U
#define DEBUG_STREAM_OSC_PARAM_COGGING_IQ     0x0040U
#define DEBUG_STREAM_OSC_PARAM_VBUS_VOLTAGE   0x0080U
#define DEBUG_STREAM_OSC_PARAM_IQ_TARGET      0x0100U
#define DEBUG_STREAM_OSC_PARAM_IQ_MEASURED    0x0200U

/* Scheduler precomputed dividers. */
#define FOC_SCHEDULER_CONTROL_DIVIDER  (FOC_SCHEDULER_TICK_HZ / FOC_SCHEDULER_CONTROL_HZ)
#define FOC_SCHEDULER_SERVICE_DIVIDER   (FOC_SCHEDULER_TICK_HZ / FOC_SCHEDULER_SERVICE_HZ)
#define FOC_SCHEDULER_MONITOR_DIVIDER   (FOC_SCHEDULER_TICK_HZ / FOC_SCHEDULER_MONITOR_HZ)
#define FOC_SCHEDULER_HEARTBEAT_DIVIDER (FOC_SCHEDULER_TICK_HZ / FOC_SCHEDULER_HEARTBEAT_HZ)

#endif /* FOC_CFG_SYMBOL_DEFS_H */
