#ifndef FOC_CFG_FEATURE_SWITCHES_H
#define FOC_CFG_FEATURE_SWITCHES_H

#include "LS_Config/foc_symbol_defs.h"

/* Telemetry output feature switches. */
#define DEBUG_STREAM_ENABLE_SEMANTIC_REPORT FOC_CFG_ENABLE
#define DEBUG_STREAM_ENABLE_OSC_REPORT FOC_CFG_ENABLE

/* Diagnostics feature switches. */
#define FOC_FEATURE_DIAG_OUTPUT FOC_CFG_ENABLE
#define FOC_FEATURE_DIAG_STATS FOC_CFG_ENABLE

/* Safety feature switches. */
#define FOC_FEATURE_UNDERVOLTAGE_PROTECTION FOC_CFG_ENABLE

/* Sensing feature switches. */
#define FOC_SENSOR_KALMAN_CURRENT_ENABLE FOC_CFG_ENABLE
#define FOC_SENSOR_KALMAN_ANGLE_ENABLE FOC_CFG_DISABLE
#define FOC_SENSOR_ANGLE_LPF_ENABLE FOC_CFG_ENABLE

/* Modulation and control feature switches. */
#define FOC_CURRENT_LOOP_PID_ENABLE FOC_CFG_ENABLE
#define FOC_CURRENT_SOFT_SWITCH_ENABLE FOC_CFG_ENABLE
#define FOC_CURRENT_LOOP_IQ_LPF_ENABLE FOC_CFG_DISABLE
#define FOC_SVPWM_PRE_LPF_ENABLE FOC_CFG_DISABLE
#define FOC_ZERO_VECTOR_CLAMP_ENABLE FOC_CFG_DISABLE

/* Initialization and calibration feature switches. */
#define FOC_INIT_CALIBRATION_ENABLE FOC_CFG_ENABLE

#define FOC_COGGING_COMP_ENABLE FOC_CFG_ENABLE
#define FOC_COGGING_CALIB_ENABLE FOC_CFG_ENABLE

/*
 * Protocol command trimming switches.
 *
 * The minimal control protocol set is always enabled and not guarded by these
 * macros: P:A/R/S/D, S:M, Y:R/C.
 */
#define FOC_PROTOCOL_ENABLE_SENSOR_SAMPLE_OFFSET FOC_CFG_ENABLE
#define FOC_PROTOCOL_ENABLE_TELEMETRY_REPORT FOC_CFG_ENABLE
#define FOC_PROTOCOL_ENABLE_CURRENT_PID_TUNING FOC_CFG_ENABLE
#define FOC_PROTOCOL_ENABLE_ANGLE_PID_TUNING FOC_CFG_DISABLE
#define FOC_PROTOCOL_ENABLE_SPEED_PID_TUNING FOC_CFG_DISABLE
#define FOC_PROTOCOL_ENABLE_CONTROL_FINE_TUNING FOC_CFG_DISABLE
#define FOC_PROTOCOL_ENABLE_CURRENT_SOFT_SWITCH FOC_CFG_DISABLE
#define FOC_PROTOCOL_ENABLE_COGGING_COMP FOC_CFG_ENABLE

/* Control build and startup motion defaults. */
#define FOC_BUILD_CONTROL_ALGO_SET FOC_CTRL_ALGO_BUILD_FULL

#endif /* FOC_CFG_FEATURE_SWITCHES_H */
