#ifndef DEBUG_STREAM_H
#define DEBUG_STREAM_H

#include <stdint.h>

#include "foc_control.h"
#include "sensor.h"

#define DEBUG_STREAM_ENABLE_SEMANTIC_REPORT   1
#define DEBUG_STREAM_ENABLE_OSC_REPORT        1

#define DEBUG_STREAM_OSC_HEAD_BYTE     0x61U
#define DEBUG_STREAM_OSC_TAIL_BYTE     0x62U

#define DEBUG_STREAM_OSC_PARAM_CURRENT_A      0x0001U
#define DEBUG_STREAM_OSC_PARAM_CURRENT_B      0x0002U
#define DEBUG_STREAM_OSC_PARAM_CURRENT_C      0x0004U
#define DEBUG_STREAM_OSC_PARAM_ANGLE_FILTERED 0x0008U
#define DEBUG_STREAM_OSC_PARAM_ANGLE_ACCUM    0x0010U
#define DEBUG_STREAM_OSC_PARAM_EXEC_TIME_US   0x0020U

#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_A       1U
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_B       1U
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_C       1U
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_FILTERED  1U
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_ACCUM     1U
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_EXEC_TIME_US    1U

#define DEBUG_STREAM_OSC_DEFAULT_PARAM_MASK ( \
	((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_A != 0U) ? DEBUG_STREAM_OSC_PARAM_CURRENT_A : 0U) | \
	((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_B != 0U) ? DEBUG_STREAM_OSC_PARAM_CURRENT_B : 0U) | \
	((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_C != 0U) ? DEBUG_STREAM_OSC_PARAM_CURRENT_C : 0U) | \
	((DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_FILTERED != 0U) ? DEBUG_STREAM_OSC_PARAM_ANGLE_FILTERED : 0U) | \
	((DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_ACCUM != 0U) ? DEBUG_STREAM_OSC_PARAM_ANGLE_ACCUM : 0U) | \
	((DEBUG_STREAM_OSC_DEFAULT_SHOW_EXEC_TIME_US != 0U) ? DEBUG_STREAM_OSC_PARAM_EXEC_TIME_US : 0U) )

void DebugStream_Init(void);
void DebugStream_Process(const sensor_data_t *sensor, const foc_motor_t *motor);

#endif /* DEBUG_STREAM_H */
