#ifndef FOC_CONFIG_SENSING_H
#define FOC_CONFIG_SENSING_H

#include "math_transforms.h"

/* Sensor sampling phase offset percent in one PWM period (0.0f ~ 100.0f). */
#define FOC_APP_SENSOR_SAMPLE_OFFSET_PERCENT_DEFAULT 96.0f

/* Kalman default parameters: (measurement_error, estimate_error, process_noise, initial). */
#define FOC_SENSOR_KALMAN_CURRENT_A_MEAS_ERR 0.15f
#define FOC_SENSOR_KALMAN_CURRENT_A_EST_ERR 0.0f
#define FOC_SENSOR_KALMAN_CURRENT_A_PROC_NOISE 0.025f
#define FOC_SENSOR_KALMAN_CURRENT_A_INIT 0.0f

#define FOC_SENSOR_KALMAN_CURRENT_B_MEAS_ERR 0.15f
#define FOC_SENSOR_KALMAN_CURRENT_B_EST_ERR 0.0f
#define FOC_SENSOR_KALMAN_CURRENT_B_PROC_NOISE 0.02f
#define FOC_SENSOR_KALMAN_CURRENT_B_INIT 0.0f

#define FOC_SENSOR_KALMAN_ANGLE_MEAS_ERR 1.0f
#define FOC_SENSOR_KALMAN_ANGLE_EST_ERR 5.0f
#define FOC_SENSOR_KALMAN_ANGLE_PROC_NOISE 0.05f
#define FOC_SENSOR_KALMAN_ANGLE_INIT 0.0f

#endif /* FOC_CONFIG_SENSING_H */
