#ifndef FOC_CONFIG_RUNTIME_PARAMS_H
#define FOC_CONFIG_RUNTIME_PARAMS_H

#include "foc_config_telemetry.h"
#include "foc_config_timing.h"

/* Command runtime parameter ranges (unit: rad / rad/s / PID gains). */
#define COMMAND_MANAGER_PARAM_TARGET_ANGLE_MIN_RAD (-12.566f)
#define COMMAND_MANAGER_PARAM_TARGET_ANGLE_MAX_RAD (12.566f)

#define COMMAND_MANAGER_PARAM_ANGLE_SPEED_MIN_RAD_S (0.0f)
#define COMMAND_MANAGER_PARAM_ANGLE_SPEED_MAX_RAD_S (200.0f)

#define COMMAND_MANAGER_PARAM_PID_CURRENT_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KP_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_CURRENT_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KI_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_CURRENT_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_PID_ANGLE_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KP_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_ANGLE_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KI_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_ANGLE_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_PID_SPEED_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KP_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_SPEED_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KI_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_SPEED_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KD_MAX (10.0f)

/* Report frequency range (Hz), bounded by monitor task trigger rate. */
#define COMMAND_MANAGER_PARAM_REPORT_FREQ_MIN_HZ (1.0f)
#define COMMAND_MANAGER_PARAM_REPORT_FREQ_MAX_HZ ((float)FOC_SCHEDULER_MONITOR_HZ)

/* Osc parameter mask range (16-bit payload mask). */
#define COMMAND_MANAGER_PARAM_OSC_MASK_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_OSC_MASK_MAX (65535.0f)

/* Control mode selector range. */
#define COMMAND_MANAGER_PARAM_CONTROL_MODE_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_CONTROL_MODE_MAX (1.0f)

/* Generic non-negative range for control runtime config writes. */
#define COMMAND_MANAGER_PARAM_NON_NEGATIVE_MIN (0.0f)

#endif /* FOC_CONFIG_RUNTIME_PARAMS_H */
