#ifndef FOC_CONFIG_RUNTIME_PARAMS_H
#define FOC_CONFIG_RUNTIME_PARAMS_H

#include "foc_config_telemetry.h"

/* Control mode options. */
#define COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE 0U
#define COMMAND_MANAGER_CONTROL_MODE_SPEED_ONLY 1U
#define COMMAND_MANAGER_ENABLED_DISABLE 0U
#define COMMAND_MANAGER_ENABLED_ENABLE 1U

/* Runtime parameter defaults. */
#define COMMAND_MANAGER_DEFAULT_SEMANTIC_DIV 5U
#define COMMAND_MANAGER_DEFAULT_OSC_DIV 1U
#define COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED 1U
#define COMMAND_MANAGER_DEFAULT_OSC_ENABLED 0U
#define COMMAND_MANAGER_DEFAULT_OSC_PARAM_MASK DEBUG_STREAM_OSC_DEFAULT_PARAM_MASK

/* Command runtime parameter ranges (unit: rad / rad/s / PID gains). */
#define COMMAND_MANAGER_PARAM_TARGET_ANGLE_MIN_RAD (-12.566f)
#define COMMAND_MANAGER_PARAM_TARGET_ANGLE_MAX_RAD (12.566f)

#define COMMAND_MANAGER_PARAM_ANGLE_SPEED_MIN_RAD_S (0.0f)
#define COMMAND_MANAGER_PARAM_ANGLE_SPEED_MAX_RAD_S (200.0f)

#define COMMAND_MANAGER_PARAM_PID_CURRENT_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KP_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_CURRENT_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KI_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_CURRENT_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_PID_ANGLE_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KP_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_ANGLE_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KI_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_ANGLE_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_PID_SPEED_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KP_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_SPEED_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KI_MAX (50.0f)

#define COMMAND_MANAGER_PARAM_PID_SPEED_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KD_MAX (10.0f)

/* Divider range: used by semantic and osc stream decimation. */
#define COMMAND_MANAGER_PARAM_REPORT_DIV_MIN (1.0f)
#define COMMAND_MANAGER_PARAM_REPORT_DIV_MAX (1000.0f)

/* Osc parameter mask range (16-bit payload mask). */
#define COMMAND_MANAGER_PARAM_OSC_MASK_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_OSC_MASK_MAX (65535.0f)

/* Control mode selector range. */
#define COMMAND_MANAGER_PARAM_CONTROL_MODE_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_CONTROL_MODE_MAX (1.0f)

/* Generic non-negative range for control runtime config writes. */
#define COMMAND_MANAGER_PARAM_NON_NEGATIVE_MIN (0.0f)

#endif /* FOC_CONFIG_RUNTIME_PARAMS_H */
