#ifndef FOC_CONFIG_TIMING_H
#define FOC_CONFIG_TIMING_H

/* Platform clock basis used by timer period conversion (unit: kHz). */
#define FOC_PLATFORM_BASE_CLOCK_KHZ 120000U
/* Timer1 control-loop source setup for 1kHz tick on current clock tree. */
#define FOC_PLATFORM_CONTROL_TIMER_PRESCALER 11999U
#define FOC_PLATFORM_CONTROL_TIMER_PERIOD 9U

#define FOC_SCHEDULER_TICK_HZ 1000U

#define FOC_SCHEDULER_SERVICE_HZ 100U
#define FOC_SCHEDULER_MONITOR_HZ 10U
#define FOC_SCHEDULER_HEARTBEAT_HZ 1U

#if (FOC_SCHEDULER_TICK_HZ == 0U) || (FOC_SCHEDULER_SERVICE_HZ == 0U) || (FOC_SCHEDULER_MONITOR_HZ == 0U) || (FOC_SCHEDULER_HEARTBEAT_HZ == 0U)
#error "Scheduler frequency macros must be non-zero"
#endif

#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_SERVICE_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_SERVICE_HZ"
#endif

#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_MONITOR_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_MONITOR_HZ"
#endif

#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_HEARTBEAT_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_HEARTBEAT_HZ"
#endif

#define FOC_SCHEDULER_SERVICE_DIVIDER   (FOC_SCHEDULER_TICK_HZ / FOC_SCHEDULER_SERVICE_HZ)
#define FOC_SCHEDULER_MONITOR_DIVIDER   (FOC_SCHEDULER_TICK_HZ / FOC_SCHEDULER_MONITOR_HZ)
#define FOC_SCHEDULER_HEARTBEAT_DIVIDER (FOC_SCHEDULER_TICK_HZ / FOC_SCHEDULER_HEARTBEAT_HZ)

#endif /* FOC_CONFIG_TIMING_H */
