#ifndef FOC_CONFIG_CONTROL_H
#define FOC_CONFIG_CONTROL_H

#include "math_transforms.h"

#define FOC_SPEED_ERR_ACCUM_LIMIT_RAD (MATH_TWO_PI * 4.0f)
#define FOC_SPEED_MECH_REBASE_RAD 2048.0f
#define FOC_DEFAULT_MIN_MECH_ANGLE_ACCUM_DELTA_RAD 0.001f
#define FOC_DEFAULT_ANGLE_HOLD_INTEGRAL_LIMIT 0.2f
#define FOC_DEFAULT_ANGLE_HOLD_PID_DEADBAND_RAD 0.002f

#define FOC_DEFAULT_SPEED_ANGLE_TRANSITION_START_RAD 0.40f
#define FOC_DEFAULT_SPEED_ANGLE_TRANSITION_END_RAD 0.60f
#endif /* FOC_CONFIG_CONTROL_H */