#ifndef FOC_CONFIG_STARTUP_H
#define FOC_CONFIG_STARTUP_H

#include "foc_shared_types.h"

/* Telemetry and diagnostic output configuration. */
#define DEBUG_STREAM_ENABLE_SEMANTIC_REPORT 1
#define DEBUG_STREAM_ENABLE_OSC_REPORT 1

/* Diagnostic output and statistics trimming switches. */
#define FOC_FEATURE_DIAG_OUTPUT 1U
#define FOC_FEATURE_DIAG_STATS 1U

/*
 * Control-algorithm build set selection.
 * Note: SPEED_ONLY and SPEED_ANGLE are parallel algorithms, not feature superset/subset.
 * FULL keeps both algorithms and allows runtime mode switching.
 */
#define FOC_BUILD_CONTROL_ALGO_SET FOC_CTRL_ALGO_BUILD_FULL

#define FOC_CTRL_ALGO_BUILD_FULL 0U
#define FOC_CTRL_ALGO_BUILD_SPEED_ONLY 1U
#define FOC_CTRL_ALGO_BUILD_SPEED_ANGLE_ONLY 2U
#if ((FOC_FEATURE_DIAG_OUTPUT != 0U) && (FOC_FEATURE_DIAG_OUTPUT != 1U))
#error "FOC_FEATURE_DIAG_OUTPUT must be 0 or 1"
#endif

#if ((FOC_FEATURE_DIAG_STATS != 0U) && (FOC_FEATURE_DIAG_STATS != 1U))
#error "FOC_FEATURE_DIAG_STATS must be 0 or 1"
#endif

#if ((FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_FULL) && \
	(FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_SPEED_ONLY) && \
	(FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_SPEED_ANGLE_ONLY))
#error "FOC_BUILD_CONTROL_ALGO_SET must be a valid FOC_CTRL_ALGO_BUILD_* value"
#endif

/* Default motor init parameters for board bring-up and calibration. */
#define FOC_APP_MOTOR_INIT_VBUS_DEFAULT 12.0f
#define FOC_APP_MOTOR_INIT_SET_VOLTAGE_DEFAULT 11.4f
#define FOC_APP_MOTOR_INIT_PHASE_RES_DEFAULT 13.2f
#define FOC_APP_MOTOR_INIT_POLE_PAIRS_DEFAULT 7U
#define FOC_APP_MOTOR_INIT_MECH_ZERO_DEFAULT_RAD 3.157f
#define FOC_APP_MOTOR_INIT_DIRECTION_DEFAULT FOC_DIR_REVERSED
/* Default SVPWM deadtime percent used by app init. */
#define FOC_APP_SVPWM_DEADTIME_PERCENT_DEFAULT 2U

/* Control defaults. */
#define COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE 1U
#if (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_SPEED_ONLY)
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ONLY
#else
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE
#endif
#define COMMAND_MANAGER_DEFAULT_TARGET_ANGLE_RAD 3.14f
#define COMMAND_MANAGER_DEFAULT_ANGLE_SPEED_RAD_S 16.0f

/* PID default gains. */
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KP 0.0f
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KI 0.0f
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KD 0.0f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KP 2.0f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KI 0.8f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KD 0.01f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KP 3.0f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KI 0.5f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KD 0.0f

#endif /* FOC_CONFIG_STARTUP_H */
