#ifndef FOC_CFG_COMPILE_LIMITS_H
#define FOC_CFG_COMPILE_LIMITS_H

/* Runtime parameter ranges (unit: rad / rad/s / PID gains). */
#define COMMAND_MANAGER_PARAM_TARGET_ANGLE_MIN_RAD (-12.566f)
#define COMMAND_MANAGER_PARAM_TARGET_ANGLE_MAX_RAD (12.566f)
#define COMMAND_MANAGER_PARAM_ANGLE_SPEED_MIN_RAD_S (0.0f)
#define COMMAND_MANAGER_PARAM_ANGLE_SPEED_MAX_RAD_S (200.0f)

#define COMMAND_MANAGER_PARAM_PID_CURRENT_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KP_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KI_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_PID_ANGLE_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KP_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KI_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_PID_SPEED_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KP_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KI_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_REPORT_FREQ_MIN_HZ (1.0f)
#define COMMAND_MANAGER_PARAM_REPORT_FREQ_MAX_HZ ((float)FOC_SCHEDULER_MONITOR_HZ)
#define COMMAND_MANAGER_PARAM_OSC_MASK_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_OSC_MASK_MAX (65535.0f)
#define COMMAND_MANAGER_PARAM_CONTROL_MODE_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_CONTROL_MODE_MAX (1.0f)
#define COMMAND_MANAGER_PARAM_NON_NEGATIVE_MIN (0.0f)

/* Unified enable or disable compile-time checks. */
#if ((DEBUG_STREAM_ENABLE_SEMANTIC_REPORT != FOC_CFG_DISABLE) && (DEBUG_STREAM_ENABLE_SEMANTIC_REPORT != FOC_CFG_ENABLE))
#error "DEBUG_STREAM_ENABLE_SEMANTIC_REPORT must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((DEBUG_STREAM_ENABLE_OSC_REPORT != FOC_CFG_DISABLE) && (DEBUG_STREAM_ENABLE_OSC_REPORT != FOC_CFG_ENABLE))
#error "DEBUG_STREAM_ENABLE_OSC_REPORT must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_FEATURE_DIAG_OUTPUT != FOC_CFG_DISABLE) && (FOC_FEATURE_DIAG_OUTPUT != FOC_CFG_ENABLE))
#error "FOC_FEATURE_DIAG_OUTPUT must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_FEATURE_DIAG_STATS != FOC_CFG_DISABLE) && (FOC_FEATURE_DIAG_STATS != FOC_CFG_ENABLE))
#error "FOC_FEATURE_DIAG_STATS must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_FEATURE_UNDERVOLTAGE_PROTECTION != FOC_CFG_DISABLE) && (FOC_FEATURE_UNDERVOLTAGE_PROTECTION != FOC_CFG_ENABLE))
#error "FOC_FEATURE_UNDERVOLTAGE_PROTECTION must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_SENSOR_KALMAN_CURRENT_ENABLE != FOC_CFG_DISABLE) && (FOC_SENSOR_KALMAN_CURRENT_ENABLE != FOC_CFG_ENABLE))
#error "FOC_SENSOR_KALMAN_CURRENT_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_SENSOR_KALMAN_ANGLE_ENABLE != FOC_CFG_DISABLE) && (FOC_SENSOR_KALMAN_ANGLE_ENABLE != FOC_CFG_ENABLE))
#error "FOC_SENSOR_KALMAN_ANGLE_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_CURRENT_LOOP_PID_ENABLE != FOC_CFG_DISABLE) && (FOC_CURRENT_LOOP_PID_ENABLE != FOC_CFG_ENABLE))
#error "FOC_CURRENT_LOOP_PID_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_SVPWM_PRE_LPF_ENABLE != FOC_CFG_DISABLE) && (FOC_SVPWM_PRE_LPF_ENABLE != FOC_CFG_ENABLE))
#error "FOC_SVPWM_PRE_LPF_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_ZERO_VECTOR_CLAMP_ENABLE != FOC_CFG_DISABLE) && (FOC_ZERO_VECTOR_CLAMP_ENABLE != FOC_CFG_ENABLE))
#error "FOC_ZERO_VECTOR_CLAMP_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif

/* Runtime default booleans also follow unified semantics. */
#if ((COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED != FOC_CFG_DISABLE) && (COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED != FOC_CFG_ENABLE))
#error "COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((COMMAND_MANAGER_DEFAULT_OSC_ENABLED != FOC_CFG_DISABLE) && (COMMAND_MANAGER_DEFAULT_OSC_ENABLED != FOC_CFG_ENABLE))
#error "COMMAND_MANAGER_DEFAULT_OSC_ENABLED must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE != FOC_CFG_DISABLE) && (COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE != FOC_CFG_ENABLE))
#error "COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif

/* Scheduler and platform constraints. */
#if (FOC_PLATFORM_BASE_CLOCK_KHZ == 0U) || (FOC_PLATFORM_CONTROL_TIMER_FREQ_KHZ == 0U)
#error "Platform timer frequency macros must be non-zero"
#endif
#if (FOC_PLATFORM_BASE_CLOCK_KHZ % FOC_PLATFORM_CONTROL_TIMER_FREQ_KHZ) != 0U
#error "FOC_PLATFORM_BASE_CLOCK_KHZ must be divisible by FOC_PLATFORM_CONTROL_TIMER_FREQ_KHZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ == 0U) || (FOC_SCHEDULER_CONTROL_HZ == 0U) || (FOC_SCHEDULER_SERVICE_HZ == 0U) || (FOC_SCHEDULER_MONITOR_HZ == 0U) || (FOC_SCHEDULER_HEARTBEAT_HZ == 0U)
#error "Scheduler frequency macros must be non-zero"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_CONTROL_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_CONTROL_HZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_SERVICE_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_SERVICE_HZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_MONITOR_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_MONITOR_HZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_HEARTBEAT_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_HEARTBEAT_HZ"
#endif

/* Build-set constraints. */
#if ((FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_FULL) && \
     (FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_SPEED_ONLY) && \
     (FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_SPEED_ANGLE_ONLY))
#error "FOC_BUILD_CONTROL_ALGO_SET must be a valid FOC_CTRL_ALGO_BUILD_* value"
#endif

/*
 * Runtime range constraints for float-valued macros are validated at runtime paths.
 * ARMCC preprocessor in this toolchain accepts only integral expressions in #if.
 */

#define DEBUG_STREAM_OSC_DEFAULT_PARAM_MASK ( \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_A != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_CURRENT_A : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_B != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_CURRENT_B : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_C != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_CURRENT_C : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_FILTERED != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_ANGLE_FILTERED : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_ACCUM != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_ANGLE_ACCUM : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_EXEC_TIME_US != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_EXEC_TIME_US : 0U))

#define COMMAND_MANAGER_DEFAULT_OSC_PARAM_MASK DEBUG_STREAM_OSC_DEFAULT_PARAM_MASK


#endif /* FOC_CFG_COMPILE_LIMITS_H */