#ifndef FOC_CONFIG_CONTROL_H
#define FOC_CONFIG_CONTROL_H

#include "math_transforms.h"

/* Control mode options. */
#define COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE 0U
#define COMMAND_MANAGER_CONTROL_MODE_SPEED_ONLY 1U

#define COMMAND_MANAGER_ENABLED_DISABLE 0U
#define COMMAND_MANAGER_ENABLED_ENABLE 1U

#define FOC_SPEED_ERR_ACCUM_LIMIT_RAD (MATH_TWO_PI * 4.0f)
#define FOC_SPEED_MECH_REBASE_RAD 2048.0f
#define FOC_DEFAULT_MIN_MECH_ANGLE_ACCUM_DELTA_RAD 0.001f
#define FOC_DEFAULT_ANGLE_HOLD_INTEGRAL_LIMIT 0.2f
#define FOC_DEFAULT_ANGLE_HOLD_PID_DEADBAND_RAD 0.002f

#define FOC_DEFAULT_SPEED_ANGLE_TRANSITION_START_RAD 0.40f
#define FOC_DEFAULT_SPEED_ANGLE_TRANSITION_END_RAD 0.60f

/* Control defaults. */
#define COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE 1U
#if (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_SPEED_ONLY)
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ONLY
#else
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE
#endif
#define COMMAND_MANAGER_DEFAULT_TARGET_ANGLE_RAD 3.14f
#define COMMAND_MANAGER_DEFAULT_ANGLE_SPEED_RAD_S 16.0f

/* PID default gains. */
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KP 0.0f
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KI 0.0f
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KD 0.0f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KP 2.0f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KI 0.8f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KD 0.01f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KP 3.0f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KI 0.5f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KD 0.0f


#endif /* FOC_CONFIG_CONTROL_H */