#ifndef FOC_CONFIG_COMM_H
#define FOC_CONFIG_COMM_H

/* Protocol frame and parser constants. */
#define PROTOCOL_PARSER_FRAME_HEAD_DEFAULT 'a'
#define PROTOCOL_PARSER_FRAME_TAIL_DEFAULT 'b'
#define PROTOCOL_PARSER_STATUS_OK_CHAR 'O'
#define PROTOCOL_PARSER_STATUS_FRAME_ERROR_CHAR 'E'
#define PROTOCOL_PARSER_STATUS_TIMEOUT_CHAR 'T'
#define PROTOCOL_PARSER_RX_MAX_LEN 128U
#define PROTOCOL_PARSER_MIN_FRAME_LEN 4U

/* Command group definitions. */
#define COMMAND_MANAGER_CMD_WRITE_PARAM 'W'
#define COMMAND_MANAGER_CMD_READ_PARAM 'R'
#define COMMAND_MANAGER_CMD_READ_STATE 'Q'
#define COMMAND_MANAGER_CMD_FAULT_CONTROL 'F'
#define COMMAND_MANAGER_SUBCMD_FAULT_CLEAR_REINIT 'C'

/* Parameter sub-command definitions. */
#define COMMAND_MANAGER_SUBCMD_TARGET_ANGLE 'A'
#define COMMAND_MANAGER_SUBCMD_ANGLE_SPEED 'S'
#define COMMAND_MANAGER_SUBCMD_SEMANTIC_DIV 'L'
#define COMMAND_MANAGER_SUBCMD_OSC_DIV 'H'
#define COMMAND_MANAGER_SUBCMD_SEMANTIC_ENABLE 'Y'
#define COMMAND_MANAGER_SUBCMD_OSC_ENABLE 'Z'
#define COMMAND_MANAGER_SUBCMD_OSC_PARAM_MASK 'O'
#define COMMAND_MANAGER_SUBCMD_READ_ALL 'X'

/* PID and control config sub-command definitions. */
#define COMMAND_MANAGER_SUBCMD_PID_CURRENT_KP 'C'
#define COMMAND_MANAGER_SUBCMD_PID_CURRENT_KI 'I'
#define COMMAND_MANAGER_SUBCMD_PID_CURRENT_KD 'J'
#define COMMAND_MANAGER_SUBCMD_PID_ANGLE_KP 'G'
#define COMMAND_MANAGER_SUBCMD_PID_ANGLE_KI 'K'
#define COMMAND_MANAGER_SUBCMD_PID_ANGLE_KD 'N'
#define COMMAND_MANAGER_SUBCMD_PID_SPEED_KP 'P'
#define COMMAND_MANAGER_SUBCMD_PID_SPEED_KI 'U'
#define COMMAND_MANAGER_SUBCMD_PID_SPEED_KD 'V'
#define COMMAND_MANAGER_SUBCMD_CFG_MIN_MECH_DELTA 'M'
#define COMMAND_MANAGER_SUBCMD_CFG_HOLD_I_LIMIT 'B'
#define COMMAND_MANAGER_SUBCMD_CFG_HOLD_DEADBAND 'E'
#define COMMAND_MANAGER_SUBCMD_CFG_BLEND_START 'F'
#define COMMAND_MANAGER_SUBCMD_CFG_BLEND_END 'T'
#define COMMAND_MANAGER_SUBCMD_CONTROL_MODE 'D'
#define COMMAND_MANAGER_SUBCMD_MOTOR_ENABLE 'Q'

/* Command status code definitions. */
#define COMMAND_MANAGER_STATUS_CMD_INVALID_CHAR 'I'
#define COMMAND_MANAGER_STATUS_PARAM_INVALID_CHAR 'P'

/* Communication buffering. */
#define COMMAND_MANAGER_REPLY_BUFFER_LEN 128U

#endif /* FOC_CONFIG_COMM_H */