#ifndef FOC_SYMBOL_DEFS_H
#define FOC_SYMBOL_DEFS_H

/* ========== Mathematical constants (single source of truth) ========== */
#define FOC_MATH_PI         3.1415926f
#define FOC_MATH_TWO_PI     6.2831852f
#define FOC_MATH_SQRT3      1.7320508f
#define FOC_MATH_SQRT3_BY_2 0.8660254f
#define FOC_MATH_PI_BY_3    1.0471975f
#define FOC_MATH_EPSILON    0.0f

/* ISR 架构模式枚举值 */
#define FOC_ISR_MODE_2ISR 0U
#define FOC_ISR_MODE_3ISR 1U

/* ========== 滤波器类型枚举值 ========== */
#define FOC_FILTER_TYPE_NONE    0
#define FOC_FILTER_TYPE_KALMAN  1
#define FOC_FILTER_TYPE_LPF1    2
#define FOC_FILTER_TYPE_BIQUAD  3

/* ========== 从类型值推导类型名（二次展开） ========== */
#define FOC_FILTER_TYPEDEF_0    foc_filter_none_t
#define FOC_FILTER_TYPEDEF_1    foc_filter_kalman_t
#define FOC_FILTER_TYPEDEF_2    foc_filter_lpf1_t
#define FOC_FILTER_TYPEDEF_3    foc_filter_biquad_t

#define FOC_FILTER_TYPEDEF_CONCAT_(x)  FOC_FILTER_TYPEDEF_##x
#define FOC_FILTER_TYPEDEF(id)         FOC_FILTER_TYPEDEF_CONCAT_(id)

/* Unified binary semantics for all enable or disable style macros. */
#define FOC_CFG_DISABLE 0U
#define FOC_CFG_ENABLE 1U

/* Current sense phase count: 0 = no current sensor, 2 = two-phase, 3 = three-phase. */
#define FOC_CURRENT_SENSE_NONE 0U

/* Control mode options. */
#define COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE 0U
#define COMMAND_MANAGER_CONTROL_MODE_SPEED_ONLY 1U

#define FOC_DIR_UNDEFINED 0
#define FOC_DIR_NORMAL 1
#define FOC_DIR_REVERSED -1

#define FOC_MECH_ANGLE_AT_ELEC_ZERO_UNDEFINED (-1.0f)

#define FOC_POLE_PAIRS_UNDEFINED 0U

/* Motor parameter measurement type */
#define FOC_MOTOR_MEASUREMENT_TYPE_Y_LINE         0U
#define FOC_MOTOR_MEASUREMENT_TYPE_DELTA_LINE     1U
#define FOC_MOTOR_MEASUREMENT_TYPE_PHASE_DIRECT   2U

/* Control strategy source identifiers. */
#define FOC_CONTROL_SRC_NONE        0U
#define FOC_CONTROL_SRC_ENCODER     1U
#define FOC_CONTROL_SRC_SMO         2U
#define FOC_CONTROL_SRC_HFI         3U
#define FOC_CONTROL_SRC_OPENLOOP    4U
#define FOC_CONTROL_SRC_FLUX        5U

/* Current soft-switch mode options. */
#define FOC_CURRENT_SOFT_SWITCH_MODE_OPEN 0U
#define FOC_CURRENT_SOFT_SWITCH_MODE_CLOSED 1U
#define FOC_CURRENT_SOFT_SWITCH_MODE_AUTO 2U

/* Compensation source identifiers. */
#define FOC_COGGING_COMP_SOURCE_DISABLED 0U
#define FOC_COGGING_COMP_SOURCE_NONE 1U
#define FOC_COGGING_COMP_SOURCE_STATIC 2U
#define FOC_COGGING_COMP_SOURCE_CALIB 3U

/* Runtime boolean state representation. */
/* Deprecated alias group: use FOC_CFG_DISABLE/FOC_CFG_ENABLE directly in new code. */
#define COMMAND_MANAGER_ENABLED_DISABLE FOC_CFG_DISABLE
#define COMMAND_MANAGER_ENABLED_ENABLE FOC_CFG_ENABLE

#define FOC_ESTIM_SMO_ANGLE_METHOD_PLL         0U
#define FOC_ESTIM_SMO_ANGLE_METHOD_LPF_ATAN2   1U

/* Control algorithm build set identifiers. */
#define FOC_CTRL_ALGO_BUILD_FULL 0U
#define FOC_CTRL_ALGO_BUILD_SPEED_ONLY 1U
#define FOC_CTRL_ALGO_BUILD_SPEED_ANGLE_ONLY 2U

/* Protocol frame and status chars (canonical names). */
#define FOC_PROTOCOL_FRAME_HEAD_CHAR 'a'
#define FOC_PROTOCOL_FRAME_TAIL_CHAR 'b'
#define FOC_PROTOCOL_DRIVER_ID_BROADCAST 0xFFU
#define FOC_PROTOCOL_STATUS_OK_CHAR 'O'
#define FOC_PROTOCOL_STATUS_FRAME_ERROR_CHAR 'E'
/* Reserved status char for future timeout feedback path. */
#define FOC_PROTOCOL_STATUS_TIMEOUT_CHAR 'T'

#define PROTOCOL_PARSER_RX_MAX_LEN 64U
#define PROTOCOL_PARSER_MIN_FRAME_LEN 5U

/* Command group definitions. */
#define COMMAND_MANAGER_CMD_PARAM 'P'
#define COMMAND_MANAGER_CMD_STATE 'S'
#define COMMAND_MANAGER_CMD_SYSTEM 'Y'
/* New config/tuning command group (split from P due to address space exhaustion). */
#define COMMAND_MANAGER_CMD_CONFIG 'C'

/* System sub-command definitions. */
#define COMMAND_MANAGER_SYSTEM_SUBCMD_RUNTIME_SUMMARY 'R'
#define COMMAND_MANAGER_SYSTEM_SUBCMD_FAULT_CLEAR_REINIT 'C'
#define COMMAND_MANAGER_SYSTEM_SUBCMD_COGGING_CALIB 'G'
#define COMMAND_MANAGER_SYSTEM_SUBCMD_COGGING_DUMP 'D'
#define COMMAND_MANAGER_SYSTEM_SUBCMD_COGGING_EXPORT 'T'
#define COMMAND_MANAGER_SYSTEM_SUBCMD_REINIT 'I'
#define COMMAND_MANAGER_SYSTEM_SUBCMD_INFO 'X'
#define COMMAND_MANAGER_SYSTEM_SUBCMD_ABORT 'A'

/* =================================================================
 * P 命令组（运行参数）—— 帧格式 a<P_driver><P><subcmd>[param]b
 * 保留常用运行参数，留出充足扩展空间。
 * ================================================================= */
#define COMMAND_MANAGER_PARAM_SUBCMD_TARGET_ANGLE 'A'
#define COMMAND_MANAGER_PARAM_SUBCMD_ANGLE_SPEED 'R'
#define COMMAND_MANAGER_PARAM_SUBCMD_SPEED_ONLY_SPEED 'S'
#define COMMAND_MANAGER_PARAM_SUBCMD_SENSOR_SAMPLE_OFFSET 'W'
#define COMMAND_MANAGER_PARAM_SUBCMD_SEMANTIC_DIV 'L'
#define COMMAND_MANAGER_PARAM_SUBCMD_OSC_DIV 'H'
#define COMMAND_MANAGER_PARAM_SUBCMD_OSC_PARAM_MASK 'O'
#define COMMAND_MANAGER_PARAM_SUBCMD_READ_ALL 'X'
/* CONTROL_MODE 在 P 组有 'D'，在 C 组不重复定义 */
#define COMMAND_MANAGER_PARAM_SUBCMD_CONTROL_MODE 'D'

/* =================================================================
 * C 命令组（调优/配置参数）—— 帧格式 a<driver_id><C><subcmd>[param]b
 * 从原 P 组拆分而来，包含 PID 调优、控制 fine-tuning、齿槽补偿、电流软切换。
 * 子命令仅在同一 C 组内保持唯一，与 P 组完全独立。
 * ================================================================= */

/* PID 参数（条件：FOC_PROTOCOL_ENABLE_CURRENT_PID_TUNING） */
#define COMMAND_MANAGER_CONFIG_SUBCMD_PID_CURRENT_KP 'C'
#define COMMAND_MANAGER_CONFIG_SUBCMD_PID_CURRENT_KI 'I'
#define COMMAND_MANAGER_CONFIG_SUBCMD_PID_CURRENT_KD 'J'

/* PID 角度环（条件：FOC_PROTOCOL_ENABLE_ANGLE_PID_TUNING） */
#define COMMAND_MANAGER_CONFIG_SUBCMD_PID_ANGLE_KP 'G'
#define COMMAND_MANAGER_CONFIG_SUBCMD_PID_ANGLE_KI 'K'
#define COMMAND_MANAGER_CONFIG_SUBCMD_PID_ANGLE_KD 'N'

/* PID 速度环（条件：FOC_PROTOCOL_ENABLE_SPEED_PID_TUNING） */
#define COMMAND_MANAGER_CONFIG_SUBCMD_PID_SPEED_KP 'P'
#define COMMAND_MANAGER_CONFIG_SUBCMD_PID_SPEED_KI 'S'
#define COMMAND_MANAGER_CONFIG_SUBCMD_PID_SPEED_KD 'R'

/* 控制 fine-tuning（条件：FOC_PROTOCOL_ENABLE_CONTROL_FINE_TUNING） */
#define COMMAND_MANAGER_CONFIG_SUBCMD_CFG_MIN_MECH_DELTA 'M'
#define COMMAND_MANAGER_CONFIG_SUBCMD_CFG_HOLD_I_LIMIT 'B'
#define COMMAND_MANAGER_CONFIG_SUBCMD_CFG_HOLD_DEADBAND 'E'
#define COMMAND_MANAGER_CONFIG_SUBCMD_CFG_BLEND_START 'F'
#define COMMAND_MANAGER_CONFIG_SUBCMD_CFG_BLEND_END 'T'

/* 齿槽补偿参数（条件：FOC_COGGING_CALIB_ENABLE / FOC_COGGING_COMP_ENABLE） */
#define COMMAND_MANAGER_CONFIG_SUBCMD_COGGING_CALIB_GAIN 'Y'
#define COMMAND_MANAGER_CONFIG_SUBCMD_COGGING_COMP_IQ_LIMIT 'L'
#define COMMAND_MANAGER_CONFIG_SUBCMD_COGGING_COMP_SPEED_GATE 'A'

/* 电流软切换参数（条件：FOC_CURRENT_SOFT_SWITCH_ENABLE） */
#define COMMAND_MANAGER_CONFIG_SUBCMD_CURRENT_SOFT_SWITCH_MODE 'Q'

/* C 组批量读取哨兵 */
#define COMMAND_MANAGER_CONFIG_SUBCMD_READ_ALL 'X'
#define COMMAND_MANAGER_CONFIG_SUBCMD_CURRENT_SOFT_SWITCH_AUTO_OPEN_IQ 'Z'
#define COMMAND_MANAGER_CONFIG_SUBCMD_CURRENT_SOFT_SWITCH_AUTO_CLOSED_IQ 'O'

/* 注意：以下旧宏已从 P 组移除，等效功能移至 C 组：
 *   COMMAND_MANAGER_PARAM_SUBCMD_* → COMMAND_MANAGER_CONFIG_SUBCMD_*
 *   PID_CURRENT_KP/C/I/KD, PID_ANGLE_KP/KI/KD, PID_SPEED_KP/KI/KD,
 *   CFG_MIN_MECH_DELTA/HOLD_I_LIMIT/HOLD_DEADBAND/BLEND_START/BLEND_END,
 *   COGGING_CALIB_GAIN/COMP_IQ_LIMIT/COMP_SPEED_GATE,
 *   CURRENT_SOFT_SWITCH_MODE/AUTO_OPEN_IQ/AUTO_CLOSED_IQ
 */

/* State sub-command definitions (ENABLE/DISABLE only). */
#define COMMAND_MANAGER_STATE_SUBCMD_MOTOR_ENABLE 'M'
#define COMMAND_MANAGER_STATE_SUBCMD_SEMANTIC_ENABLE 'S'
#define COMMAND_MANAGER_STATE_SUBCMD_OSC_ENABLE 'O'
#define COMMAND_MANAGER_STATE_SUBCMD_COGGING_COMP_ENABLE 'G'
#define COMMAND_MANAGER_STATE_SUBCMD_READ_ALL 'X'

/* Command status chars. */
#define COMMAND_MANAGER_STATUS_CMD_INVALID_CHAR 'I'
#define COMMAND_MANAGER_STATUS_PARAM_INVALID_CHAR 'P'

/* Communication buffering. */
#define COMMAND_MANAGER_REPLY_BUFFER_LEN 72U

/* Telemetry protocol bytes and payload symbols. */
#define FOC_OSC_CHANNEL_COUNT 16U
#define DEBUG_STREAM_OSC_PAYLOAD_LEN 80U

/* Telemetry parameter mask bits. */
#define DEBUG_STREAM_OSC_PARAM_CURRENT_A      0x0001U
#define DEBUG_STREAM_OSC_PARAM_CURRENT_B      0x0002U
#define DEBUG_STREAM_OSC_PARAM_CURRENT_C      0x0004U
#define DEBUG_STREAM_OSC_PARAM_ANGLE_ACTIVE_MECH  0x0008U
#define DEBUG_STREAM_OSC_PARAM_ANGLE_STANDBY_MECH 0x0010U
#define DEBUG_STREAM_OSC_PARAM_EXEC_TIME_US   0x0020U
#define DEBUG_STREAM_OSC_PARAM_VBUS_VOLTAGE   0x0040U
#define DEBUG_STREAM_OSC_PARAM_IQ_TARGET      0x0080U
#define DEBUG_STREAM_OSC_PARAM_IQ_MEASURED    0x0100U
#define DEBUG_STREAM_OSC_PARAM_CURRENT_A_RAW     0x0200U
#define DEBUG_STREAM_OSC_PARAM_CURRENT_B_RAW     0x0400U
#define DEBUG_STREAM_OSC_PARAM_SPEED_ACTIVE_MECH  0x0800U
#define DEBUG_STREAM_OSC_PARAM_SPEED_STANDBY_MECH 0x1000U
#define DEBUG_STREAM_OSC_PARAM_ANGLE_ACTIVE_ELEC  0x2000U
#define DEBUG_STREAM_OSC_PARAM_ANGLE_STANDBY_ELEC 0x4000U
#define DEBUG_STREAM_OSC_PARAM_PHASE_LAG          0x8000U

/* Scheduler precomputed dividers. */
#define FOC_SCHEDULER_CONTROL_DIVIDER  (FOC_SCHEDULER_TICK_HZ / FOC_SCHEDULER_CONTROL_HZ)
#define FOC_SCHEDULER_SERVICE_DIVIDER   (FOC_SCHEDULER_TICK_HZ / FOC_SCHEDULER_SERVICE_HZ)
#define FOC_SCHEDULER_MONITOR_DIVIDER   (FOC_SCHEDULER_TICK_HZ / FOC_SCHEDULER_MONITOR_HZ)
#define FOC_SCHEDULER_HEARTBEAT_DIVIDER (FOC_SCHEDULER_TICK_HZ / FOC_SCHEDULER_HEARTBEAT_HZ)

#endif /* FOC_SYMBOL_DEFS_H */
