#ifndef FOC_COMPILE_LIMITS_H
#define FOC_COMPILE_LIMITS_H

/*
 * Compile-time limits & static assertions.
 *
 * This file depends on symbols & macros from foc_symbol_defs.h,
 * foc_cfg_feature_switches.h, and foc_cfg_init_values.h.  The call sites
 * (foc_config.h) MUST include those three before including this file.
 * Direct inclusion without the prerequisites will cause "undefined
 * identifier" compilation errors.
 */

/* Runtime parameter ranges (unit: rad / rad/s / PID gains). */
#define FOC_PROTOCOL_DRIVER_ID_MIN 0x32U
#define FOC_PROTOCOL_DRIVER_ID_MAX 0x7EU

#define COMMAND_MANAGER_PARAM_TARGET_ANGLE_MIN_RAD (-100.0f)
#define COMMAND_MANAGER_PARAM_TARGET_ANGLE_MAX_RAD (100.0f)
#define COMMAND_MANAGER_PARAM_ANGLE_SPEED_MIN_RAD_S (0.0f)
#define COMMAND_MANAGER_PARAM_ANGLE_SPEED_MAX_RAD_S (20.0f)
#define COMMAND_MANAGER_PARAM_SPEED_ONLY_MIN_RAD_S (-100.0f)
#define COMMAND_MANAGER_PARAM_SPEED_ONLY_MAX_RAD_S (100.0f)
#define COMMAND_MANAGER_PARAM_SENSOR_SAMPLE_OFFSET_MIN_PERCENT (0.0f)
#define COMMAND_MANAGER_PARAM_SENSOR_SAMPLE_OFFSET_MAX_PERCENT (100.0f)

#define COMMAND_MANAGER_PARAM_PID_CURRENT_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KP_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KI_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_PID_ANGLE_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KP_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KI_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_PID_SPEED_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KP_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KI_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_REPORT_FREQ_MIN_HZ (1.0f)
#define COMMAND_MANAGER_PARAM_REPORT_FREQ_MAX_HZ ((float)FOC_SCHEDULER_MONITOR_HZ)
#define COMMAND_MANAGER_PARAM_OSC_MASK_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_OSC_MASK_MAX (65535.0f)
#define COMMAND_MANAGER_PARAM_CONTROL_MODE_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_CONTROL_MODE_MAX (1.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_MODE_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_MODE_MAX (2.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_AUTO_OPEN_IQ_MIN_A (0.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_AUTO_OPEN_IQ_MAX_A (100.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_AUTO_CLOSED_IQ_MIN_A (0.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_AUTO_CLOSED_IQ_MAX_A (100.0f)
#define COMMAND_MANAGER_PARAM_NON_NEGATIVE_MIN (0.0f)

/* Cogging compensation runtime parameter ranges. */
#define COMMAND_MANAGER_PARAM_COGGING_COMP_IQ_LIMIT_MIN_A (0.0f)
#define COMMAND_MANAGER_PARAM_COGGING_COMP_IQ_LIMIT_MAX_A (100.0f)
#define COMMAND_MANAGER_PARAM_COGGING_COMP_SPEED_GATE_MIN_RAD_S (0.0f)
#define COMMAND_MANAGER_PARAM_COGGING_COMP_SPEED_GATE_MAX_RAD_S (36.0f)

/* Soft hint output helpers for non-blocking config consistency diagnostics. */
#if defined(__ARMCC_VERSION) || defined(__GNUC__) || defined(__clang__)
#define FOC_CFG_PRAGMA_STR2(x) #x
#define FOC_CFG_PRAGMA_STR(x) FOC_CFG_PRAGMA_STR2(x)
#define FOC_CFG_DO_PRAGMA(x) _Pragma(FOC_CFG_PRAGMA_STR(x))
#define FOC_CFG_HINT(msg) FOC_CFG_DO_PRAGMA(message msg)
#else
#define FOC_CFG_HINT(msg)
#endif

/* Unified enable or disable compile-time checks. */

/* Current sense phase count: 0 = no sensor, 2 = two-phase + reconstruct, 3 = three-phase direct. */
#if (FOC_CURRENT_SENSE_PHASES != FOC_CURRENT_SENSE_NONE) && \
    (FOC_CURRENT_SENSE_PHASES != 2U) && \
    (FOC_CURRENT_SENSE_PHASES != 3U)
#error "FOC_CURRENT_SENSE_PHASES must be FOC_CURRENT_SENSE_NONE (0), 2 (two-phase + reconstruct), or 3 (three-phase direct)"
#endif

#if ((DEBUG_STREAM_ENABLE_SEMANTIC_REPORT != FOC_CFG_DISABLE) && (DEBUG_STREAM_ENABLE_SEMANTIC_REPORT != FOC_CFG_ENABLE))
#error "DEBUG_STREAM_ENABLE_SEMANTIC_REPORT must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((DEBUG_STREAM_ENABLE_OSC_REPORT != FOC_CFG_DISABLE) && (DEBUG_STREAM_ENABLE_OSC_REPORT != FOC_CFG_ENABLE))
#error "DEBUG_STREAM_ENABLE_OSC_REPORT must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_FEATURE_DIAG_OUTPUT != FOC_CFG_DISABLE) && (FOC_FEATURE_DIAG_OUTPUT != FOC_CFG_ENABLE))
#error "FOC_FEATURE_DIAG_OUTPUT must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_FEATURE_UNDERVOLTAGE_PROTECTION != FOC_CFG_DISABLE) && (FOC_FEATURE_UNDERVOLTAGE_PROTECTION != FOC_CFG_ENABLE))
#error "FOC_FEATURE_UNDERVOLTAGE_PROTECTION must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_SENSOR_ANGLE_LPF_ENABLE != FOC_CFG_DISABLE) && (FOC_SENSOR_ANGLE_LPF_ENABLE != FOC_CFG_ENABLE))
#error "FOC_SENSOR_ANGLE_LPF_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_CURRENT_LOOP_PID_ENABLE != FOC_CFG_DISABLE) && (FOC_CURRENT_LOOP_PID_ENABLE != FOC_CFG_ENABLE))
#error "FOC_CURRENT_LOOP_PID_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_CURRENT_SOFT_SWITCH_ENABLE != FOC_CFG_DISABLE) && (FOC_CURRENT_SOFT_SWITCH_ENABLE != FOC_CFG_ENABLE))
#error "FOC_CURRENT_SOFT_SWITCH_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_ZERO_VECTOR_CLAMP_ENABLE != FOC_CFG_DISABLE) && (FOC_ZERO_VECTOR_CLAMP_ENABLE != FOC_CFG_ENABLE))
#error "FOC_ZERO_VECTOR_CLAMP_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_COGGING_COMP_ENABLE != FOC_CFG_DISABLE) && (FOC_COGGING_COMP_ENABLE != FOC_CFG_ENABLE))
#error "FOC_COGGING_COMP_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_INIT_CALIBRATION_ENABLE != FOC_CFG_DISABLE) && (FOC_INIT_CALIBRATION_ENABLE != FOC_CFG_ENABLE))
#error "FOC_INIT_CALIBRATION_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_TELEMETRY_REPORT != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_TELEMETRY_REPORT != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_TELEMETRY_REPORT must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_CURRENT_PID_TUNING != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_CURRENT_PID_TUNING != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_CURRENT_PID_TUNING must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_ANGLE_PID_TUNING != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_ANGLE_PID_TUNING != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_ANGLE_PID_TUNING must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_SPEED_PID_TUNING != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_SPEED_PID_TUNING != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_SPEED_PID_TUNING must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_CONTROL_FINE_TUNING != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_CONTROL_FINE_TUNING != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_CONTROL_FINE_TUNING must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_COGGING_CALIB_ENABLE != FOC_CFG_DISABLE) && (FOC_COGGING_CALIB_ENABLE != FOC_CFG_ENABLE))
#error "FOC_COGGING_CALIB_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_REINIT_ENABLE != FOC_CFG_DISABLE) && (FOC_REINIT_ENABLE != FOC_CFG_ENABLE))
#error "FOC_REINIT_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif

/* Runtime default booleans also follow unified semantics. */
#if ((COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED != FOC_CFG_DISABLE) && (COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED != FOC_CFG_ENABLE))
#error "COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((COMMAND_MANAGER_DEFAULT_OSC_ENABLED != FOC_CFG_DISABLE) && (COMMAND_MANAGER_DEFAULT_OSC_ENABLED != FOC_CFG_ENABLE))
#error "COMMAND_MANAGER_DEFAULT_OSC_ENABLED must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE != FOC_CFG_DISABLE) && (COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE != FOC_CFG_ENABLE))
#error "COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_ENABLE != FOC_CFG_DISABLE) && (COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_ENABLE != FOC_CFG_ENABLE))
#error "COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_COGGING_STATIC_TABLE_DEFINED != FOC_CFG_DISABLE) && (FOC_COGGING_STATIC_TABLE_DEFINED != FOC_CFG_ENABLE))
#error "FOC_COGGING_STATIC_TABLE_DEFINED must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_MOTOR_INIT_MECH_ZERO_DEFINED != FOC_CFG_DISABLE) && (FOC_MOTOR_INIT_MECH_ZERO_DEFINED != FOC_CFG_ENABLE))
#error "FOC_MOTOR_INIT_MECH_ZERO_DEFINED must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif

#if ((FOC_CURRENT_SOFT_SWITCH_ENABLE == FOC_CFG_ENABLE) && (FOC_CURRENT_LOOP_PID_ENABLE != FOC_CFG_ENABLE))
#if defined(__CC_ARM) && !defined(__clang__)
#warning FOC_CFG_HINT_FEATURE_DEPENDENCY current soft-switch feature is enabled but current-loop PID is disabled; soft-switch code path is compiled out.
#else
FOC_CFG_HINT("FOC_CFG_HINT_FEATURE_DEPENDENCY: current soft-switch feature is enabled but current-loop PID is disabled; soft-switch code path is compiled out.")
#endif
#endif
/* Note: The original P:U/V subcommand conflict between speed PID tuning and
 * cogging compensation no longer applies. Both moved to C command group with
 * separate subcommand letters (C:S/R for speed PID, C:L/A for cogging comp). */
#if ((FOC_CURRENT_SOFT_SWITCH_ENABLE != FOC_CFG_ENABLE) && (COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_ENABLE == FOC_CFG_ENABLE))
#if defined(__CC_ARM) && !defined(__clang__)
#warning FOC_CFG_HINT_FEATURE_DEFAULT current soft-switch default state is ENABLE but feature is disabled; runtime will force disable.
#else
FOC_CFG_HINT("FOC_CFG_HINT_FEATURE_DEFAULT: current soft-switch default state is ENABLE but feature is disabled; runtime will force disable.")
#endif
#endif
/* Cogging calibration depends on cogging compensation feature. */
#if ((FOC_COGGING_CALIB_ENABLE == FOC_CFG_ENABLE) && (FOC_COGGING_COMP_ENABLE != FOC_CFG_ENABLE))
#error "FOC_COGGING_CALIB_ENABLE requires FOC_COGGING_COMP_ENABLE == FOC_CFG_ENABLE"
#endif


#if (FOC_COGGING_LUT_POINT_COUNT < 8U)
#error "FOC_COGGING_LUT_POINT_COUNT must be >= 8"
#endif
#if (FOC_CALIB_ZERO_LOCK_SAMPLE_COUNT == 0U)
#error "FOC_CALIB_ZERO_LOCK_SAMPLE_COUNT must be non-zero"
#endif
#if (FOC_CALIB_COARSE_STEP_COUNT == 0U)
#error "FOC_CALIB_COARSE_STEP_COUNT must be non-zero"
#endif
#if (FOC_CALIB_COARSE_STEP_SAMPLE_COUNT == 0U)
#error "FOC_CALIB_COARSE_STEP_SAMPLE_COUNT must be non-zero"
#endif

#if (FOC_INIT_CALIBRATION_ENABLE == FOC_CFG_DISABLE)
#if (FOC_MOTOR_INIT_POLE_PAIRS_DEFAULT == FOC_POLE_PAIRS_UNDEFINED)
#error "FOC_MOTOR_INIT_POLE_PAIRS_DEFAULT must be defined when init calibration is disabled"
#endif
#if (FOC_MOTOR_INIT_DIRECTION_DEFAULT == FOC_DIR_UNDEFINED)
#error "FOC_MOTOR_INIT_DIRECTION_DEFAULT must be defined when init calibration is disabled"
#endif
#if (FOC_MOTOR_INIT_MECH_ZERO_DEFINED != FOC_CFG_ENABLE)
#error "FOC_MOTOR_INIT_MECH_ZERO_DEFINED must be FOC_CFG_ENABLE when init calibration is disabled"
#endif
#endif

/* Scheduler and platform constraints. */
#if (FOC_PLATFORM_BASE_CLOCK_KHZ == 0U)
#error "Platform timer frequency macros must be non-zero"
#endif
#if (FOC_PLATFORM_BASE_CLOCK_KHZ % (FOC_SCHEDULER_TICK_HZ / 1000U)) != 0U
#error "FOC_PLATFORM_BASE_CLOCK_KHZ must be divisible by FOC_SCHEDULER_TICK_HZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ == 0U) || (FOC_SCHEDULER_CONTROL_HZ == 0U) || (FOC_SCHEDULER_SERVICE_HZ == 0U) || (FOC_SCHEDULER_MONITOR_HZ == 0U) || (FOC_SCHEDULER_HEARTBEAT_HZ == 0U)
#error "Scheduler frequency macros must be non-zero"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_CONTROL_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_CONTROL_HZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_SERVICE_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_SERVICE_HZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_MONITOR_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_MONITOR_HZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_HEARTBEAT_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_HEARTBEAT_HZ"
#endif

#if (FOC_PWM_FREQ_KHZ == 0U)
#error "FOC_PWM_FREQ_KHZ must be non-zero"
#endif
#if (FOC_CURRENT_LOOP_ISR_DIVIDER == 0U)
#error "FOC_CURRENT_LOOP_ISR_DIVIDER must be >= 1"
#endif
#if (FOC_PWM_FREQ_KHZ % FOC_CURRENT_LOOP_ISR_DIVIDER) != 0U
#error "FOC_PWM_FREQ_KHZ must be divisible by FOC_CURRENT_LOOP_ISR_DIVIDER"
#endif
#if (FOC_CURRENT_LOOP_ISR_FREQ == 0U)
#error "FOC_CURRENT_LOOP_ISR_FREQ must be non-zero (derived; check PWM freq and ISR divider)"
#endif

#if ((FOC_PROTOCOL_LOCAL_DRIVER_ID_DEFAULT != FOC_PROTOCOL_DRIVER_ID_BROADCAST) && \
     ((FOC_PROTOCOL_LOCAL_DRIVER_ID_DEFAULT < FOC_PROTOCOL_DRIVER_ID_MIN) || \
    (FOC_PROTOCOL_LOCAL_DRIVER_ID_DEFAULT > FOC_PROTOCOL_DRIVER_ID_MAX)))
#error "FOC_PROTOCOL_LOCAL_DRIVER_ID_DEFAULT must be in [FOC_PROTOCOL_DRIVER_ID_MIN, FOC_PROTOCOL_DRIVER_ID_MAX] or FOC_PROTOCOL_DRIVER_ID_BROADCAST"
#endif

/* Build-set constraints. */
#if ((FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_FULL) && \
     (FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_SPEED_ONLY) && \
     (FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_SPEED_ANGLE_ONLY))
#error "FOC_BUILD_CONTROL_ALGO_SET must be a valid FOC_CTRL_ALGO_BUILD_* value"
#endif

/*
 * Runtime range constraints for float-valued macros are validated at runtime paths.
 * ARMCC preprocessor in this toolchain accepts only integral expressions in #if.
 */

#define DEBUG_STREAM_OSC_DEFAULT_PARAM_MASK ( \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_A != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_CURRENT_A : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_B != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_CURRENT_B : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_C != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_CURRENT_C : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_ACTIVE_MECH != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_ANGLE_ACTIVE_MECH : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_STANDBY_MECH != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_ANGLE_STANDBY_MECH : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_EXEC_TIME_US != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_EXEC_TIME_US : 0U)|\
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_VBUS_VOLTAGE != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_VBUS_VOLTAGE : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_IQ_TARGET != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_IQ_TARGET : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_IQ_MEASURED != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_IQ_MEASURED : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_A_RAW != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_CURRENT_A_RAW : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_B_RAW != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_CURRENT_B_RAW : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_SPEED_ACTIVE_MECH != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_SPEED_ACTIVE_MECH : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_SPEED_STANDBY_MECH != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_SPEED_STANDBY_MECH : 0U))
    

#define COMMAND_MANAGER_DEFAULT_OSC_PARAM_MASK DEBUG_STREAM_OSC_DEFAULT_PARAM_MASK

/* ── 无感FOC新增宏合法性检查 ── */

#if ((FOC_SENSOR_ENCODER_ENABLE != FOC_CFG_DISABLE) && (FOC_SENSOR_ENCODER_ENABLE != FOC_CFG_ENABLE))
#error "FOC_SENSOR_ENCODER_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_SENSOR_ANGLE_FAST_ENABLE != FOC_CFG_DISABLE) && (FOC_SENSOR_ANGLE_FAST_ENABLE != FOC_CFG_ENABLE))
#error "FOC_SENSOR_ANGLE_FAST_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_ESTIMATOR_ENCODER_ENABLE != FOC_CFG_DISABLE) && (FOC_ESTIMATOR_ENCODER_ENABLE != FOC_CFG_ENABLE))
#error "FOC_ESTIMATOR_ENCODER_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_ESTIMATOR_SMO_ENABLE != FOC_CFG_DISABLE) && (FOC_ESTIMATOR_SMO_ENABLE != FOC_CFG_ENABLE))
#error "FOC_ESTIMATOR_SMO_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_ESTIMATOR_HFI_ENABLE != FOC_CFG_DISABLE) && (FOC_ESTIMATOR_HFI_ENABLE != FOC_CFG_ENABLE))
#error "FOC_ESTIMATOR_HFI_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_ESTIMATOR_FLUX_ENABLE != FOC_CFG_DISABLE) && (FOC_ESTIMATOR_FLUX_ENABLE != FOC_CFG_ENABLE))
#error "FOC_ESTIMATOR_FLUX_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_OPENLOOP_SOURCE_ENABLE != FOC_CFG_DISABLE) && (FOC_OPENLOOP_SOURCE_ENABLE != FOC_CFG_ENABLE))
#error "FOC_OPENLOOP_SOURCE_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_SOURCE_SWITCH_ENABLE != FOC_CFG_DISABLE) && (FOC_SOURCE_SWITCH_ENABLE != FOC_CFG_ENABLE))
#error "FOC_SOURCE_SWITCH_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif

/* 编码器估计器依赖编码器硬件 */
#if (FOC_ESTIMATOR_ENCODER_ENABLE == FOC_CFG_ENABLE) && \
    (FOC_SENSOR_ENCODER_ENABLE != FOC_CFG_ENABLE)
#error "FOC_ESTIMATOR_ENCODER_ENABLE requires FOC_SENSOR_ENCODER_ENABLE"
#endif

/* 齿槽补偿/标定依赖编码器硬件 */
#if (FOC_COGGING_COMP_ENABLE == FOC_CFG_ENABLE) && \
    (FOC_SENSOR_ENCODER_ENABLE != FOC_CFG_ENABLE)
#error "FOC_COGGING_COMP_ENABLE requires FOC_SENSOR_ENCODER_ENABLE"
#endif
#if (FOC_COGGING_CALIB_ENABLE == FOC_CFG_ENABLE) && \
    (FOC_SENSOR_ENCODER_ENABLE != FOC_CFG_ENABLE)
#error "FOC_COGGING_CALIB_ENABLE requires FOC_SENSOR_ENCODER_ENABLE"
#endif

/* 无感估计器需电流采样 */
#if ((FOC_ESTIMATOR_SMO_ENABLE == FOC_CFG_ENABLE) || \
     (FOC_ESTIMATOR_HFI_ENABLE == FOC_CFG_ENABLE)) && \
    (FOC_CURRENT_SENSE_PHASES == FOC_CURRENT_SENSE_NONE)
#error "Sensorless estimators require current sensing"
#endif

/* SMO needs at least one low-speed angle source when encoder is unavailable. */
#if (FOC_ESTIMATOR_SMO_ENABLE == FOC_CFG_ENABLE) && \
    (FOC_ESTIMATOR_ENCODER_ENABLE != FOC_CFG_ENABLE) && \
    (FOC_OPENLOOP_SOURCE_ENABLE != FOC_CFG_ENABLE) && \
    (FOC_ESTIMATOR_HFI_ENABLE != FOC_CFG_ENABLE)
#error "SMO requires at least one low-speed angle source (HFI or OPENLOOP) when encoder not available"
#endif

/* OpenLoop angle source must have pole pairs when encoder calibration is unavailable. */
#if (FOC_OPENLOOP_SOURCE_ENABLE == FOC_CFG_ENABLE) && \
    (FOC_ESTIMATOR_ENCODER_ENABLE != FOC_CFG_ENABLE) && \
    (FOC_MOTOR_INIT_POLE_PAIRS_DEFAULT == FOC_POLE_PAIRS_UNDEFINED)
#error "OpenLoop source requires a known pole count: set FOC_MOTOR_INIT_POLE_PAIRS_DEFAULT"
#endif

#if (FOC_OPENLOOP_SOURCE_ENABLE == FOC_CFG_ENABLE) && \
    (FOC_ESTIMATOR_ENCODER_ENABLE != FOC_CFG_ENABLE) && \
    (FOC_MOTOR_INIT_DIRECTION_DEFAULT == FOC_DIR_UNDEFINED)
#error "OpenLoop source requires a known direction: set FOC_MOTOR_INIT_DIRECTION_DEFAULT"
#endif

/* Source switch is derived from distinct low/high source configuration. */
#if (FOC_SOURCE_SWITCH_ENABLE == FOC_CFG_ENABLE)
#if (FOC_CONTROL_HIGH_SOURCE == FOC_CONTROL_SRC_NONE)
#error "FOC_SOURCE_SWITCH_ENABLE requires a configured high source"
#endif
#if (FOC_CONTROL_LOW_SOURCE == FOC_CONTROL_HIGH_SOURCE)
#error "FOC_SOURCE_SWITCH_ENABLE requires distinct low/high sources"
#endif
#endif

/* 确保配置的 low/high source 对应的 estimator 已启用 */
#if (FOC_CONTROL_LOW_SOURCE == FOC_CONTROL_SRC_SMO) || (FOC_CONTROL_HIGH_SOURCE == FOC_CONTROL_SRC_SMO)
#if (FOC_ESTIMATOR_SMO_ENABLE != FOC_CFG_ENABLE)
#error "SMO configured as source requires FOC_ESTIMATOR_SMO_ENABLE"
#endif
#endif
#if (FOC_CONTROL_LOW_SOURCE == FOC_CONTROL_SRC_ENCODER) || (FOC_CONTROL_HIGH_SOURCE == FOC_CONTROL_SRC_ENCODER)
#if (FOC_ESTIMATOR_ENCODER_ENABLE != FOC_CFG_ENABLE)
#error "Encoder configured as source requires FOC_ESTIMATOR_ENCODER_ENABLE"
#endif
#endif
#if (FOC_CONTROL_LOW_SOURCE == FOC_CONTROL_SRC_HFI) || (FOC_CONTROL_HIGH_SOURCE == FOC_CONTROL_SRC_HFI)
#if (FOC_ESTIMATOR_HFI_ENABLE != FOC_CFG_ENABLE)
#error "HFI configured as source requires FOC_ESTIMATOR_HFI_ENABLE"
#endif
#endif

/* 角度控制模式需要编码器或 HFI 提供可靠绝对角度 */
#define FOC_CONTROL_SRC_IS_ANGLE_CAPABLE(src) \
    ((src) == FOC_CONTROL_SRC_ENCODER || (src) == FOC_CONTROL_SRC_HFI)

#if (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_SPEED_ANGLE_ONLY)
    #if !FOC_CONTROL_SRC_IS_ANGLE_CAPABLE(FOC_CONTROL_LOW_SOURCE)
    #error "SPEED_ANGLE_ONLY requires ENCODER or HFI as low-speed source"
    #endif
    #if !FOC_CONTROL_SRC_IS_ANGLE_CAPABLE(FOC_CONTROL_HIGH_SOURCE)
    #error "SPEED_ANGLE_ONLY requires ENCODER or HFI as high-speed source"
    #endif
#elif (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_FULL)
    #if (COMMAND_MANAGER_DEFAULT_CONTROL_MODE == COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE)
        #if !FOC_CONTROL_SRC_IS_ANGLE_CAPABLE(FOC_CONTROL_LOW_SOURCE) || \
            !FOC_CONTROL_SRC_IS_ANGLE_CAPABLE(FOC_CONTROL_HIGH_SOURCE)
        #error "Default SPEED_ANGLE mode requires ENCODER or HFI as both sources"
        #endif
    #endif
#endif

#endif /* FOC_COMPILE_LIMITS_H */
