#ifndef FOC_CFG_INIT_VALUES_H
#define FOC_CFG_INIT_VALUES_H

#include "LS_Config/foc_symbol_defs.h"
#include "LS_Config/foc_cfg_feature_switches.h"

/* Platform timing base and timer source setup. */
#define FOC_PLATFORM_BASE_CLOCK_KHZ 120000U

/*PWM initialization defaults.*/
#define FOC_PWM_FREQ_KHZ                24U
#define FOC_SENSOR_SAMPLE_FREQ_KHZ      FOC_PWM_FREQ_KHZ
#define FOC_SVPWM_DEADTIME_PERCENT_DEFAULT 5U

/* Scheduler rates. */
#define FOC_SCHEDULER_TICK_HZ 1000U
#define FOC_SCHEDULER_CONTROL_HZ 1000U
#define FOC_SCHEDULER_SERVICE_HZ 100U
#define FOC_SCHEDULER_MONITOR_HZ 200U
#define FOC_SCHEDULER_HEARTBEAT_HZ 1U

/* 双 ISR 模式：电流环为PWMISR分频，分频仅作为降低计算负担，仍需保证执行时间小于 PWMISR 周期 */
#define FOC_CURRENT_LOOP_ISR_DIVIDER   3U
#define FOC_CURRENT_LOOP_ISR_FREQ      (FOC_PWM_FREQ_KHZ / FOC_CURRENT_LOOP_ISR_DIVIDER)

/* 三 ISR 模式：电流环独立 ISR 频率（Hz），与 PWM 频率解耦 */
#define FOC_CURRENT_LOOP_ISR_FREQ_HZ   8000U
#define FOC_CONTROL_DT_SEC             (1.0f / (float)FOC_SCHEDULER_CONTROL_HZ)

/* 电流环周期（秒）：按 FOC_CURRENT_LOOP_ISR_MODE 收敛的唯一真值，所有电流环 ISR 内模块统一使用
 * - 双 ISR 模式：PWM ISR 分频后 = 1 / 电流环ISR频率（FOC_CURRENT_LOOP_ISR_FREQ 单位 kHz）
 * - 三 ISR 模式：1 / FOC_CURRENT_LOOP_ISR_FREQ_HZ，为 0 时退化为控制周期 */
#if (FOC_CURRENT_LOOP_ISR_MODE == FOC_ISR_MODE_2ISR)
#define FOC_CURRENT_LOOP_DT_SEC        (1.0f / ((float)FOC_CURRENT_LOOP_ISR_FREQ * 1000.0f))
#elif (FOC_CURRENT_LOOP_ISR_MODE == FOC_ISR_MODE_3ISR)
#define FOC_CURRENT_LOOP_DT_SEC        ((FOC_CURRENT_LOOP_ISR_FREQ_HZ == 0U) ? \
                                        FOC_CONTROL_DT_SEC : \
                                        (1.0f / (float)FOC_CURRENT_LOOP_ISR_FREQ_HZ))
#else
#error "FOC_CURRENT_LOOP_ISR_MODE must be FOC_ISR_MODE_2ISR or FOC_ISR_MODE_3ISR"
#endif

 /* ── 电机模型参数 ── */
#define FOC_MOTOR_MEASUREMENT_TYPE     FOC_MOTOR_MEASUREMENT_TYPE_PHASE_DIRECT
#define FOC_MOTOR_INIT_STATOR_INDUCTANCE_HENRY   0.0015f
#define FOC_MOTOR_INIT_RESISTANCE_OHM 7.5f

/* Alignment/calibration voltage is derived from max_phase_voltage. */
#define FOC_MOTOR_INIT_MECH_ZERO_DEFINED FOC_CFG_ENABLE
#define FOC_MOTOR_INIT_POLE_PAIRS_DEFAULT FOC_POLE_PAIRS_UNDEFINED//
#define FOC_MOTOR_INIT_MECH_ZERO_DEFAULT_RAD FOC_MECH_ANGLE_AT_ELEC_ZERO_UNDEFINED//
#define FOC_MOTOR_INIT_DIRECTION_DEFAULT FOC_DIR_UNDEFINED

/* Motor initialization parameters. */
#define FOC_MOTOR_INIT_VBUS_DEFAULT 12.0f
#define FOC_MOTOR_INIT_MAX_PHASE_VOLTAGE_DEFAULT 12.0f
/* max_phase_voltage 限制相电压幅值(≤ VBUS)，用于 PID 饱和、过调制限制、电流计算。 */
#define FOC_SVPWM_MAX_DUTY_CYCLE 0.92f
/* max_duty_cycle 限制 SVPWM 占空比对称上限(如 0.85 → duty∈[0.15,0.85])，
 * 避免低侧电流采样落入开关噪声/下半桥关断区域*/

 /* Control mode default selection and initialization. */
#if (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_FULL)
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ONLY
#elif (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_SPEED_ONLY)
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ONLY
#elif (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_SPEED_ANGLE_ONLY)
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE
#endif
#define COMMAND_MANAGER_DEFAULT_TARGET_ANGLE_RAD 3.14f
#define COMMAND_MANAGER_DEFAULT_ANGLE_SPEED_RAD_S 5.0f
#define COMMAND_MANAGER_DEFAULT_SPEED_ONLY_RAD_S 5.0f

/* Initialization calibration strategy defaults (coarse + fine subdivision). */
#define FOC_CALIB_ALIGN_VOLTAGE_RATIO 0.40f
#define FOC_CALIB_SETTLE_MS 4U
#define FOC_CALIB_MIN_MECH_STEP_RAD 0.0015f
#define FOC_CALIB_ZERO_LOCK_SETTLE_MS 120U
#define FOC_CALIB_ZERO_LOCK_SAMPLE_COUNT 24U

#define FOC_CALIB_COARSE_STEP_COUNT 30U
#define FOC_CALIB_FINE_STEP_COUNT 60U
#define FOC_CALIB_COARSE_STEP_ELEC_RAD (FOC_MATH_TWO_PI / (float)FOC_CALIB_COARSE_STEP_COUNT)
#define FOC_CALIB_FINE_STEP_ELEC_RAD (FOC_MATH_TWO_PI / (float)FOC_CALIB_FINE_STEP_COUNT)
#define FOC_CALIB_COARSE_STEP_SETTLE_MS 4U
#define FOC_CALIB_COARSE_STEP_SAMPLE_COUNT 2U
#define FOC_CALIB_FINE_STEP_SETTLE_MS 6U
#define FOC_CALIB_FINE_STEP_SAMPLE_COUNT 4U

/* Cogging compensation defaults (optional feature). */
#define FOC_COGGING_LUT_POINT_COUNT 512U
#define FOC_COGGING_CALIB_GAIN_K      0.06f
#define FOC_COGGING_COMP_SPEED_GATE_RAD_S 15.0f

/* Cogging calibration (user-triggered, runtime) defaults. */
#define FOC_COGGING_CALIB_NUM_PASSES  2U
#define FOC_COGGING_CALIB_SPEED_RAD_S 0.4f
#define FOC_COGGING_CALIB_IQ_A        0.30f
#define FOC_COGGING_CALIB_SETTLE_CYCLES  150U

#define FOC_COGGING_CALIB_DTHETA_SCALE  50.0f
#define FOC_COGGING_BOUNDARY_Q15_THRESHOLD 100
#define FOC_COGGING_BOUNDARY_BLEND_WIN     3
#define FOC_COGGING_LUT_IQ_LSB_A 0.005f
#define FOC_COGGING_COMP_IQ_LIMIT_A 0.50f

#define FOC_COGGING_STATIC_TABLE_DEFINED FOC_CFG_ENABLE

/* Runtime default flags and rates. */
#define COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED FOC_CFG_DISABLE
#define COMMAND_MANAGER_DEFAULT_OSC_ENABLED FOC_CFG_DISABLE
#define COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE FOC_CFG_ENABLE
#define COMMAND_MANAGER_DEFAULT_SEMANTIC_FREQ_HZ 2U
#define COMMAND_MANAGER_DEFAULT_OSC_FREQ_HZ 100U

/* Telemetry default parameter visibility switches and derived mask. */
#define FOC_PROTOCOL_LOCAL_DRIVER_ID_DEFAULT 0x61U

#define DEBUG_STREAM_OSC_HEAD_BYTE 0x61U
#define DEBUG_STREAM_OSC_TAIL_BYTE 0x62U
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_A FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_B FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_C FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_ACTIVE_MECH  FOC_CFG_ENABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_STANDBY_MECH FOC_CFG_ENABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_EXEC_TIME_US FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_VBUS_VOLTAGE FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_IQ_TARGET FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_IQ_MEASURED FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_A_RAW FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_B_RAW FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_SPEED_ACTIVE_MECH  FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_SPEED_STANDBY_MECH FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_ACTIVE_ELEC  FOC_CFG_ENABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_STANDBY_ELEC FOC_CFG_ENABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_PHASE_LAG FOC_CFG_DISABLE

/* Sensor and filter initialization defaults. */
#define FOC_SENSOR_SAMPLE_OFFSET_PERCENT_DEFAULT 48.0f

/* Sensor zero-calibration defaults (stationary current offset sampling). */
#define SENSOR_ZERO_CALIB_SAMPLES            200U
#define SENSOR_ZERO_CALIB_NEAR_ZERO_CURRENT  0.15f
#define SENSOR_ZERO_CALIB_MIN_VALID_SAMPLES  160U
#define SENSOR_ZERO_CALIB_MAX_ABS_CURRENT    2.50f
#define SENSOR_ZERO_CALIB_MAX_SPREAD_CURRENT 2.50f

/* Safety threshold defaults. */
#define FOC_DIAG_SENSOR_FAULT_THRESHOLD 1U
#define FOC_UNDERVOLTAGE_TRIP_VBUS_DEFAULT 8.0f

/* Control loop defaults and limits. */
#define FOC_DEFAULT_MIN_MECH_ANGLE_ACCUM_DELTA_RAD 0.001f
#define FOC_DEFAULT_ANGLE_HOLD_INTEGRAL_LIMIT 0.03f
#define FOC_DEFAULT_ANGLE_HOLD_PID_DEADBAND_RAD 0.005f

#define FOC_DEFAULT_SPEED_ANGLE_TRANSITION_START_RAD 0.2f
#define FOC_DEFAULT_SPEED_ANGLE_TRANSITION_END_RAD 0.6f
#define FOC_SPEED_ERR_ACCUM_LIMIT_RAD (FOC_MATH_TWO_PI * 4.0f)

#define FOC_ZERO_VECTOR_CLAMP_VOLTAGE_THRESHOLD_V 0.05f

/* PID default gains. */
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KP 1.7f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KI 0.8f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KD 0.0f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KP 1.8f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KI 0.6f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KD 0.02f

#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KP 12.0f
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KI 90.0f
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KD 0.00f

/* Current-loop anti-noise and soft-switch defaults. */
#define COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_ENABLE FOC_CFG_ENABLE
#define COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_MODE FOC_CURRENT_SOFT_SWITCH_MODE_CLOSED
/*使用FOC_CURRENT_SOFT_SWITCH_MODE_AUTO以抑制低电流采样噪声，非必要不开启，会带来区间抖震以及降低控制带宽 */
#define COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_AUTO_OPEN_IQ_A 0.00f
#define COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_AUTO_CLOSED_IQ_A 0.30f

#define FOC_CURRENT_SOFT_SWITCH_BLEND_TAU_DEFAULT_SEC 0.40f

/* Queue configuration (can be overridden before including LS_Config). */
#define FOC_RX_QUEUE_DEPTH          4U
#define FOC_OUTPUT_QUEUE_DEPTH      24U
#define FOC_OUTPUT_FRAME_MAX_LEN    96U
#define FOC_OUTPUT_MAX_PER_CYCLE    12U

/* Monitor element queue (ISR → main-loop snapshot handoff). */
#define FOC_MONITOR_ELEM_QUEUE_DEPTH        32U
#define FOC_MONITOR_MAX_DEQUEUE_PER_CYCLE   24U

/* RX polling: max frames to enqueue per ServiceTrigger call.
 * 0 = auto (poll all 4 comm sources, one frame per source at most);
 * 1..4 = fixed max frames per trigger (round-robin across sources);
 * larger values allow higher throughput when service rate is low.
 */
#define FOC_COMM_MAX_FRAMES_PER_SERVICE  0U

/*LED initialization defaults. */
#define FOC_LED_RUN_INDEX 2U
#define FOC_LED_COMM_INDEX 1U
#define FOC_LED_ERROR_INDEX 3U
#define FOC_LED_RUN_BLINK_HALF_PERIOD_TICKS 1000U
#define FOC_LED_COMM_PULSE_TICKS 10U

/* ── SMO默认参数 ── */
/* ── SMO 角度估计方法 ── */
#define FOC_ESTIM_SMO_ANGLE_METHOD             FOC_ESTIM_SMO_ANGLE_METHOD_PLL//FOC_ESTIM_SMO_ANGLE_METHOD_PLL

#define FOC_ESTIM_SMO_PLL_KP_DEFAULT         150.0f
#define FOC_ESTIM_SMO_PLL_KI_DEFAULT         450.0f
#define FOC_ESTIM_SMO_CONVERGE_BEMF_V        0.05f
#define FOC_ESTIM_SMO_CONVERGE_CONSECUTIVE   50U
#define FOC_ESTIM_SMO_LOCK_CONSECUTIVE       100U
#define FOC_ESTIM_SMO_DIVERGE_CONSECUTIVE    200U
#define FOC_ESTIM_SMO_ROT_DIR_CONSECUTIVE    20U
#define FOC_ESTIM_SMO_DQ_TRACKING_THRESHOLD  0.1f
#define FOC_ESTIM_SMO_SAT_CURRENT_A          0.10f
#define FOC_ESTIM_SMO_BEMF_LPF_FC            200.0f
#define FOC_ESTIM_SMO_SPEED_LPF_FC           5.0f

#define FOC_ESTIM_SMO_K_SLIDE_DEFAULT        0.6f


/* ── OpenLoop angle source / low-speed policy defaults ── */
#define FOC_OPENLOOP_CURRENT_A                   0.4f

/* ── Source Manager 低/高速 source 切换默认参数/门限 ── */
#define FOC_ACCEL_SPEED_LIMIT_LOW_RAD_S      20.0f   /* LOW 区域速度上限 */
#define FOC_ACCEL_SPEED_LIMIT_HIGH_RAD_S     50.0f   /* HIGH/FULL 区域速度上限 */

#define FOC_SOURCE_SWITCH_SETTLE_CYCLES              200U
#define FOC_SOURCE_SWITCH_DEGRADE_CONFIRM_CYCLES     20U   /* 降域(回LOW)确认拍数，更敏捷；升域用 SETTLE_CYCLES */
#define FOC_SMO_ACCEL_PRECONV_SPEED_THRESHOLD_RAD_S  5.0f /* 预收敛速度门限 */
#define FOC_SOURCE_SWITCH_SPEED_THRESH_HIGH_DEFAULT  (FOC_ACCEL_SPEED_LIMIT_LOW_RAD_S - 2.5f)
#define FOC_SOURCE_SWITCH_SPEED_THRESH_LOW_DEFAULT   (FOC_ACCEL_SPEED_LIMIT_LOW_RAD_S - 5.0f)
#define FOC_SOURCE_SWITCH_SPEED_SCALE 0.9f   /* 升域进入真实速度容差，须满足 high_th*SCALE > low_th 保证正滞回 */

/* ── 全域加速器默认参数 ── */
#define FOC_ACCEL_RAMP_RATE_LOW_RAD_S2       20.0f    /* LOW 区域加速度 */
#define FOC_ACCEL_RAMP_RATE_HIGH_RAD_S2      20.0f   /* HIGH/FULL 区域加速度 */

#endif/* FOC_CFG_INIT_VALUES_H */
