#ifndef FOC_CFG_FEATURE_SWITCHES_H
#define FOC_CFG_FEATURE_SWITCHES_H

/* Telemetry output feature switches. */
#define DEBUG_STREAM_ENABLE_SEMANTIC_REPORT FOC_CFG_ENABLE
#define DEBUG_STREAM_ENABLE_OSC_REPORT FOC_CFG_ENABLE

/* Diagnostics feature switches. */
#define FOC_FEATURE_DIAG_OUTPUT FOC_CFG_ENABLE
#define FOC_FEATURE_DIAG_STATS FOC_CFG_ENABLE

/* Safety feature switches. */
#define FOC_FEATURE_UNDERVOLTAGE_PROTECTION FOC_CFG_DISABLE

/* Sensing feature switches. */
#define FOC_SENSOR_KALMAN_CURRENT_ENABLE FOC_CFG_DISABLE
#define FOC_SENSOR_KALMAN_ANGLE_ENABLE FOC_CFG_DISABLE
#define FOC_SENSOR_ANGLE_LPF_ENABLE FOC_CFG_ENABLE

/* Modulation and control feature switches. */
#define FOC_CURRENT_LOOP_PID_ENABLE FOC_CFG_ENABLE
#define FOC_SVPWM_PRE_LPF_ENABLE FOC_CFG_DISABLE
#define FOC_ZERO_VECTOR_CLAMP_ENABLE FOC_CFG_DISABLE

/* Control build and startup motion defaults. */
#define FOC_BUILD_CONTROL_ALGO_SET FOC_CTRL_ALGO_BUILD_FULL

#endif /* FOC_CFG_FEATURE_SWITCHES_H */
