#ifndef FOC_CFG_COMPILE_LIMITS_H
#define FOC_CFG_COMPILE_LIMITS_H

/* Runtime parameter ranges (unit: rad / rad/s / PID gains). */
#define FOC_PROTOCOL_DRIVER_ID_MIN 0x32U
#define FOC_PROTOCOL_DRIVER_ID_MAX 0x7EU

#define COMMAND_MANAGER_PARAM_TARGET_ANGLE_MIN_RAD (-100.0f)
#define COMMAND_MANAGER_PARAM_TARGET_ANGLE_MAX_RAD (100.0f)
#define COMMAND_MANAGER_PARAM_ANGLE_SPEED_MIN_RAD_S (0.0f)
#define COMMAND_MANAGER_PARAM_ANGLE_SPEED_MAX_RAD_S (36.0f)
#define COMMAND_MANAGER_PARAM_SPEED_ONLY_MIN_RAD_S (-36.0f)
#define COMMAND_MANAGER_PARAM_SPEED_ONLY_MAX_RAD_S (36.0f)
#define COMMAND_MANAGER_PARAM_SENSOR_SAMPLE_OFFSET_MIN_PERCENT (0.0f)
#define COMMAND_MANAGER_PARAM_SENSOR_SAMPLE_OFFSET_MAX_PERCENT (100.0f)

#define COMMAND_MANAGER_PARAM_PID_CURRENT_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KP_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KI_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_CURRENT_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_PID_ANGLE_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KP_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KI_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_ANGLE_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_PID_SPEED_KP_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KP_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KI_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KI_MAX (50.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KD_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_PID_SPEED_KD_MAX (10.0f)

#define COMMAND_MANAGER_PARAM_REPORT_FREQ_MIN_HZ (1.0f)
#define COMMAND_MANAGER_PARAM_REPORT_FREQ_MAX_HZ ((float)FOC_SCHEDULER_MONITOR_HZ)
#define COMMAND_MANAGER_PARAM_OSC_MASK_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_OSC_MASK_MAX (65535.0f)
#define COMMAND_MANAGER_PARAM_CONTROL_MODE_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_CONTROL_MODE_MAX (1.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_MODE_MIN (0.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_MODE_MAX (2.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_AUTO_OPEN_IQ_MIN_A (0.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_AUTO_OPEN_IQ_MAX_A (100.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_AUTO_CLOSED_IQ_MIN_A (0.0f)
#define COMMAND_MANAGER_PARAM_CURRENT_SOFT_SWITCH_AUTO_CLOSED_IQ_MAX_A (100.0f)
#define COMMAND_MANAGER_PARAM_NON_NEGATIVE_MIN (0.0f)

/* Unified enable or disable compile-time checks. */
#if ((DEBUG_STREAM_ENABLE_SEMANTIC_REPORT != FOC_CFG_DISABLE) && (DEBUG_STREAM_ENABLE_SEMANTIC_REPORT != FOC_CFG_ENABLE))
#error "DEBUG_STREAM_ENABLE_SEMANTIC_REPORT must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((DEBUG_STREAM_ENABLE_OSC_REPORT != FOC_CFG_DISABLE) && (DEBUG_STREAM_ENABLE_OSC_REPORT != FOC_CFG_ENABLE))
#error "DEBUG_STREAM_ENABLE_OSC_REPORT must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_FEATURE_DIAG_OUTPUT != FOC_CFG_DISABLE) && (FOC_FEATURE_DIAG_OUTPUT != FOC_CFG_ENABLE))
#error "FOC_FEATURE_DIAG_OUTPUT must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_FEATURE_DIAG_STATS != FOC_CFG_DISABLE) && (FOC_FEATURE_DIAG_STATS != FOC_CFG_ENABLE))
#error "FOC_FEATURE_DIAG_STATS must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_FEATURE_UNDERVOLTAGE_PROTECTION != FOC_CFG_DISABLE) && (FOC_FEATURE_UNDERVOLTAGE_PROTECTION != FOC_CFG_ENABLE))
#error "FOC_FEATURE_UNDERVOLTAGE_PROTECTION must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_SENSOR_KALMAN_CURRENT_ENABLE != FOC_CFG_DISABLE) && (FOC_SENSOR_KALMAN_CURRENT_ENABLE != FOC_CFG_ENABLE))
#error "FOC_SENSOR_KALMAN_CURRENT_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_SENSOR_KALMAN_ANGLE_ENABLE != FOC_CFG_DISABLE) && (FOC_SENSOR_KALMAN_ANGLE_ENABLE != FOC_CFG_ENABLE))
#error "FOC_SENSOR_KALMAN_ANGLE_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_SENSOR_ANGLE_LPF_ENABLE != FOC_CFG_DISABLE) && (FOC_SENSOR_ANGLE_LPF_ENABLE != FOC_CFG_ENABLE))
#error "FOC_SENSOR_ANGLE_LPF_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_CURRENT_LOOP_PID_ENABLE != FOC_CFG_DISABLE) && (FOC_CURRENT_LOOP_PID_ENABLE != FOC_CFG_ENABLE))
#error "FOC_CURRENT_LOOP_PID_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_CURRENT_SOFT_SWITCH_ENABLE != FOC_CFG_DISABLE) && (FOC_CURRENT_SOFT_SWITCH_ENABLE != FOC_CFG_ENABLE))
#error "FOC_CURRENT_SOFT_SWITCH_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_SVPWM_PRE_LPF_ENABLE != FOC_CFG_DISABLE) && (FOC_SVPWM_PRE_LPF_ENABLE != FOC_CFG_ENABLE))
#error "FOC_SVPWM_PRE_LPF_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_ZERO_VECTOR_CLAMP_ENABLE != FOC_CFG_DISABLE) && (FOC_ZERO_VECTOR_CLAMP_ENABLE != FOC_CFG_ENABLE))
#error "FOC_ZERO_VECTOR_CLAMP_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_COGGING_COMP_ENABLE != FOC_CFG_DISABLE) && (FOC_COGGING_COMP_ENABLE != FOC_CFG_ENABLE))
#error "FOC_COGGING_COMP_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_COGGING_INIT_LEARN_ENABLE != FOC_CFG_DISABLE) && (FOC_COGGING_INIT_LEARN_ENABLE != FOC_CFG_ENABLE))
#error "FOC_COGGING_INIT_LEARN_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_COGGING_DEBUG_DUMP_ENABLE != FOC_CFG_DISABLE) && (FOC_COGGING_DEBUG_DUMP_ENABLE != FOC_CFG_ENABLE))
#error "FOC_COGGING_DEBUG_DUMP_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_INIT_CALIBRATION_ENABLE != FOC_CFG_DISABLE) && (FOC_INIT_CALIBRATION_ENABLE != FOC_CFG_ENABLE))
#error "FOC_INIT_CALIBRATION_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_SENSOR_SAMPLE_OFFSET != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_SENSOR_SAMPLE_OFFSET != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_SENSOR_SAMPLE_OFFSET must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_TELEMETRY_REPORT != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_TELEMETRY_REPORT != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_TELEMETRY_REPORT must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_CURRENT_PID_TUNING != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_CURRENT_PID_TUNING != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_CURRENT_PID_TUNING must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_ANGLE_PID_TUNING != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_ANGLE_PID_TUNING != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_ANGLE_PID_TUNING must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_SPEED_PID_TUNING != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_SPEED_PID_TUNING != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_SPEED_PID_TUNING must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_CONTROL_FINE_TUNING != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_CONTROL_FINE_TUNING != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_CONTROL_FINE_TUNING must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_CURRENT_SOFT_SWITCH != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_CURRENT_SOFT_SWITCH != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_CURRENT_SOFT_SWITCH must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_COGGING_COMP != FOC_CFG_DISABLE) && (FOC_PROTOCOL_ENABLE_COGGING_COMP != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_COGGING_COMP must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif

/* Runtime default booleans also follow unified semantics. */
#if ((COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED != FOC_CFG_DISABLE) && (COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED != FOC_CFG_ENABLE))
#error "COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((COMMAND_MANAGER_DEFAULT_OSC_ENABLED != FOC_CFG_DISABLE) && (COMMAND_MANAGER_DEFAULT_OSC_ENABLED != FOC_CFG_ENABLE))
#error "COMMAND_MANAGER_DEFAULT_OSC_ENABLED must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE != FOC_CFG_DISABLE) && (COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE != FOC_CFG_ENABLE))
#error "COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_ENABLE != FOC_CFG_DISABLE) && (COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_ENABLE != FOC_CFG_ENABLE))
#error "COMMAND_MANAGER_DEFAULT_CURRENT_SOFT_SWITCH_ENABLE must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_COGGING_STATIC_TABLE_DEFINED != FOC_CFG_DISABLE) && (FOC_COGGING_STATIC_TABLE_DEFINED != FOC_CFG_ENABLE))
#error "FOC_COGGING_STATIC_TABLE_DEFINED must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif
#if ((FOC_MOTOR_INIT_MECH_ZERO_DEFINED != FOC_CFG_DISABLE) && (FOC_MOTOR_INIT_MECH_ZERO_DEFINED != FOC_CFG_ENABLE))
#error "FOC_MOTOR_INIT_MECH_ZERO_DEFINED must be FOC_CFG_ENABLE or FOC_CFG_DISABLE"
#endif

#if ((FOC_CURRENT_SOFT_SWITCH_ENABLE == FOC_CFG_ENABLE) && (FOC_CURRENT_LOOP_PID_ENABLE != FOC_CFG_ENABLE))
#error "FOC_CURRENT_SOFT_SWITCH_ENABLE requires FOC_CURRENT_LOOP_PID_ENABLE == FOC_CFG_ENABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_CURRENT_SOFT_SWITCH == FOC_CFG_ENABLE) && (FOC_CURRENT_SOFT_SWITCH_ENABLE != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_CURRENT_SOFT_SWITCH requires FOC_CURRENT_SOFT_SWITCH_ENABLE == FOC_CFG_ENABLE"
#endif
#if ((FOC_PROTOCOL_ENABLE_COGGING_COMP == FOC_CFG_ENABLE) && (FOC_COGGING_COMP_ENABLE != FOC_CFG_ENABLE))
#error "FOC_PROTOCOL_ENABLE_COGGING_COMP requires FOC_COGGING_COMP_ENABLE == FOC_CFG_ENABLE"
#endif

#if (FOC_COGGING_LUT_POINT_COUNT < 8U)
#error "FOC_COGGING_LUT_POINT_COUNT must be >= 8"
#endif
#if (FOC_COGGING_LEARN_SAMPLE_COUNT == 0U)
#error "FOC_COGGING_LEARN_SAMPLE_COUNT must be non-zero"
#endif
#if (FOC_COGGING_LEARN_MIN_VALID_PERCENT > 100U)
#error "FOC_COGGING_LEARN_MIN_VALID_PERCENT must be in [0, 100]"
#endif

#if (FOC_INIT_CALIBRATION_ENABLE == FOC_CFG_DISABLE)
#if (FOC_MOTOR_INIT_POLE_PAIRS_DEFAULT == FOC_POLE_PAIRS_UNDEFINED)
#error "FOC_MOTOR_INIT_POLE_PAIRS_DEFAULT must be defined when init calibration is disabled"
#endif
#if (FOC_MOTOR_INIT_DIRECTION_DEFAULT == FOC_DIR_UNDEFINED)
#error "FOC_MOTOR_INIT_DIRECTION_DEFAULT must be defined when init calibration is disabled"
#endif
#if (FOC_MOTOR_INIT_MECH_ZERO_DEFINED != FOC_CFG_ENABLE)
#error "FOC_MOTOR_INIT_MECH_ZERO_DEFINED must be FOC_CFG_ENABLE when init calibration is disabled"
#endif
#endif

/* Scheduler and platform constraints. */
#if (FOC_PLATFORM_BASE_CLOCK_KHZ == 0U)
#error "Platform timer frequency macros must be non-zero"
#endif
#if (FOC_PLATFORM_BASE_CLOCK_KHZ % (FOC_SCHEDULER_TICK_HZ / 1000U)) != 0U
#error "FOC_PLATFORM_BASE_CLOCK_KHZ must be divisible by FOC_SCHEDULER_TICK_HZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ == 0U) || (FOC_SCHEDULER_CONTROL_HZ == 0U) || (FOC_SCHEDULER_SERVICE_HZ == 0U) || (FOC_SCHEDULER_MONITOR_HZ == 0U) || (FOC_SCHEDULER_HEARTBEAT_HZ == 0U)
#error "Scheduler frequency macros must be non-zero"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_CONTROL_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_CONTROL_HZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_SERVICE_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_SERVICE_HZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_MONITOR_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_MONITOR_HZ"
#endif
#if (FOC_SCHEDULER_TICK_HZ % FOC_SCHEDULER_HEARTBEAT_HZ) != 0U
#error "FOC_SCHEDULER_TICK_HZ must be divisible by FOC_SCHEDULER_HEARTBEAT_HZ"
#endif

#if ((FOC_PROTOCOL_LOCAL_DRIVER_ID_DEFAULT != FOC_PROTOCOL_DRIVER_ID_BROADCAST) && \
     ((FOC_PROTOCOL_LOCAL_DRIVER_ID_DEFAULT < FOC_PROTOCOL_DRIVER_ID_MIN) || \
    (FOC_PROTOCOL_LOCAL_DRIVER_ID_DEFAULT > FOC_PROTOCOL_DRIVER_ID_MAX)))
#error "FOC_PROTOCOL_LOCAL_DRIVER_ID_DEFAULT must be in [FOC_PROTOCOL_DRIVER_ID_MIN, FOC_PROTOCOL_DRIVER_ID_MAX] or FOC_PROTOCOL_DRIVER_ID_BROADCAST"
#endif

/* Build-set constraints. */
#if ((FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_FULL) && \
     (FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_SPEED_ONLY) && \
     (FOC_BUILD_CONTROL_ALGO_SET != FOC_CTRL_ALGO_BUILD_SPEED_ANGLE_ONLY))
#error "FOC_BUILD_CONTROL_ALGO_SET must be a valid FOC_CTRL_ALGO_BUILD_* value"
#endif

/*
 * Runtime range constraints for float-valued macros are validated at runtime paths.
 * ARMCC preprocessor in this toolchain accepts only integral expressions in #if.
 */

#define DEBUG_STREAM_OSC_DEFAULT_PARAM_MASK ( \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_A != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_CURRENT_A : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_B != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_CURRENT_B : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_C != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_CURRENT_C : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_FILTERED != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_ANGLE_FILTERED : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_ACCUM != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_ANGLE_ACCUM : 0U) | \
    ((DEBUG_STREAM_OSC_DEFAULT_SHOW_EXEC_TIME_US != FOC_CFG_DISABLE) ? DEBUG_STREAM_OSC_PARAM_EXEC_TIME_US : 0U))

#define COMMAND_MANAGER_DEFAULT_OSC_PARAM_MASK DEBUG_STREAM_OSC_DEFAULT_PARAM_MASK


#endif /* FOC_CFG_COMPILE_LIMITS_H */
