#ifndef FOC_CFG_INIT_VALUES_H
#define FOC_CFG_INIT_VALUES_H

/* Platform timing base and timer source setup. */
#define FOC_PLATFORM_BASE_CLOCK_KHZ 120000U
#define FOC_PLATFORM_CONTROL_TIMER_FREQ_KHZ 1U

/* Scheduler rates. */
#define FOC_SCHEDULER_TICK_HZ 1000U

#define FOC_SCHEDULER_CONTROL_HZ 1000U

#define FOC_SCHEDULER_SERVICE_HZ 100U
#define FOC_SCHEDULER_MONITOR_HZ 200U
#define FOC_SCHEDULER_HEARTBEAT_HZ 1U

#define FOC_PWM_FREQ_KHZ                24U
#define FOC_SENSOR_SAMPLE_FREQ_KHZ      FOC_PWM_FREQ_KHZ
#define FOC_CONTROL_DT_SEC              (1.0f / (float)FOC_SCHEDULER_CONTROL_HZ)

/* I2C loop-based wait/delay budgets (non-precise, no DWT dependency). */
#define FOC_I2C_WAIT_LOOP_MAX 12000U
#define FOC_I2C_UNLOCK_HALF_PULSE_LOOP 600U
#define FOC_I2C_UNLOCK_STOP_LOOP 600U

/* Motor initialization parameters. */
#define FOC_MOTOR_INIT_VBUS_DEFAULT 12.0f
#define FOC_MOTOR_INIT_SET_VOLTAGE_DEFAULT 11.4f
#define FOC_MOTOR_INIT_PHASE_RES_DEFAULT 13.2f

#define FOC_MOTOR_INIT_POLE_PAIRS_DEFAULT 7U
#define FOC_MOTOR_INIT_MECH_ZERO_DEFAULT_RAD 3.157f
#define FOC_MOTOR_INIT_DIRECTION_DEFAULT FOC_DIR_REVERSED


/* Control mode default selection and initialization. */
#if (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_FULL)
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE
#elif (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_SPEED_ONLY)
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ONLY
#elif (FOC_BUILD_CONTROL_ALGO_SET == FOC_CTRL_ALGO_BUILD_SPEED_ANGLE_ONLY)
#define COMMAND_MANAGER_DEFAULT_CONTROL_MODE COMMAND_MANAGER_CONTROL_MODE_SPEED_ANGLE
#endif
#define COMMAND_MANAGER_DEFAULT_TARGET_ANGLE_RAD 3.14f
#define COMMAND_MANAGER_DEFAULT_ANGLE_SPEED_RAD_S 8.0f


/* Runtime default flags and rates. */
#define COMMAND_MANAGER_DEFAULT_SEMANTIC_ENABLED FOC_CFG_DISABLE
#define COMMAND_MANAGER_DEFAULT_OSC_ENABLED FOC_CFG_DISABLE
#define COMMAND_MANAGER_DEFAULT_MOTOR_ENABLE FOC_CFG_ENABLE
#define COMMAND_MANAGER_DEFAULT_SEMANTIC_FREQ_HZ 2U
#define COMMAND_MANAGER_DEFAULT_OSC_FREQ_HZ 50U

/* Telemetry default parameter visibility switches and derived mask. */
#define DEBUG_STREAM_OSC_HEAD_BYTE 0x61U
#define DEBUG_STREAM_OSC_TAIL_BYTE 0x62U
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_A FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_B FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_CURRENT_C FOC_CFG_DISABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_FILTERED FOC_CFG_ENABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_ANGLE_ACCUM FOC_CFG_ENABLE
#define DEBUG_STREAM_OSC_DEFAULT_SHOW_EXEC_TIME_US FOC_CFG_DISABLE


/* Sensor and filter initialization defaults. */
#define FOC_SENSOR_SAMPLE_OFFSET_PERCENT_DEFAULT 96.0f

#define FOC_SENSOR_KALMAN_CURRENT_A_MEAS_ERR 0.15f
#define FOC_SENSOR_KALMAN_CURRENT_A_EST_ERR 0.0f
#define FOC_SENSOR_KALMAN_CURRENT_A_PROC_NOISE 0.025f
#define FOC_SENSOR_KALMAN_CURRENT_A_INIT 0.0f
#define FOC_SENSOR_KALMAN_CURRENT_B_MEAS_ERR 0.15f
#define FOC_SENSOR_KALMAN_CURRENT_B_EST_ERR 0.0f
#define FOC_SENSOR_KALMAN_CURRENT_B_PROC_NOISE 0.02f
#define FOC_SENSOR_KALMAN_CURRENT_B_INIT 0.0f
#define FOC_SENSOR_KALMAN_ANGLE_MEAS_ERR 0.01f
#define FOC_SENSOR_KALMAN_ANGLE_EST_ERR 0.001f
#define FOC_SENSOR_KALMAN_ANGLE_PROC_NOISE 0.001f
#define FOC_SENSOR_KALMAN_ANGLE_INIT 0.0f

/* Safety threshold defaults. */
#define FOC_DIAG_SENSOR_FAULT_THRESHOLD 20U
#define FOC_UNDERVOLTAGE_TRIP_VBUS_DEFAULT 9.0f
#define FOC_UNDERVOLTAGE_RECOVER_VBUS_DEFAULT 9.5f

/* Control loop defaults and limits. */
#define FOC_SPEED_ERR_ACCUM_LIMIT_RAD (FOC_MATH_TWO_PI * 4.0f)
/* Unused-macro audit tag: RESERVED_OR_LEGACY_CANDIDATE (pending classification). */
#define FOC_SPEED_MECH_REBASE_RAD 2048.0f
#define FOC_DEFAULT_MIN_MECH_ANGLE_ACCUM_DELTA_RAD 0.001f
#define FOC_DEFAULT_ANGLE_HOLD_INTEGRAL_LIMIT 0.2f
#define FOC_DEFAULT_ANGLE_HOLD_PID_DEADBAND_RAD 0.005f
#define FOC_DEFAULT_SPEED_ANGLE_TRANSITION_START_RAD 0.40f
#define FOC_DEFAULT_SPEED_ANGLE_TRANSITION_END_RAD 0.60f

#define FOC_SVPWM_PRE_LPF_ALPHA 0.60f
#define FOC_ZERO_VECTOR_CLAMP_VOLTAGE_THRESHOLD_V 0.1f

/* PID default gains. */
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KP 0.0f
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KI 0.0f
#define COMMAND_MANAGER_DEFAULT_PID_CURRENT_KD 0.0f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KP 2.0f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KI 0.8f
#define COMMAND_MANAGER_DEFAULT_PID_ANGLE_KD 0.01f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KP 1.5f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KI 0.8f
#define COMMAND_MANAGER_DEFAULT_PID_SPEED_KD 0.01f

/* App-level SVPWM and LED initialization defaults. */
#define FOC_SVPWM_DEADTIME_PERCENT_DEFAULT 2U

#define FOC_LED_RUN_INDEX 1U
#define FOC_LED_COMM_INDEX 2U
#define FOC_LED_FAULT_INDEX 3U
#define FOC_LED_RUN_BLINK_HALF_PERIOD_TICKS 100U
#define FOC_LED_COMM_PULSE_TICKS 10U

#endif /* FOC_CFG_INIT_VALUES_H */
